/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { BusinessInfo, Service } from './types';

export const BUSINESS_INFO: BusinessInfo = {
  name: "Chuadanga Event Planner",
  owner: "MD SHAHIN",
  phones: ["01717445854", "01825052535"],
  whatsapp: "01717445854",
  email: "bondhuttoflowerhouse@gmail.com",
  facebook: "https://www.facebook.com/weddingplanningcd",
};

const EngagementCeremonyPackages = [
  {
    id: "basic",
    name: "Basic Package",
    priceRange: "10k – 15k",
    description: "Simple yet elegant decoration for intimate gatherings.",
    images: [
      "https://i.ibb.co.com/jPVScbsp/Consuelo-Hernandez-JPG-jpg.jpg",
      "https://i.ibb.co.com/d0sN1pkn/Create-unforgettable-memories-with-our-elegant-setups-JPG-jpg.jpg",
      "https://i.ibb.co.com/hJx59CWL/Mohammad-Tanveer-JPG-jpg.jpg",
      "https://i.ibb.co.com/21Gyv2fn/Tajinder-Sehmi-JPG-jpg.jpg",
      "https://i.ibb.co.com/spHmQgYf/JPG-jpg.jpg"
    ],
  },
  {
    id: "standard",
    name: "Standard Package",
    priceRange: "15k – 35k",
    description: "Beautiful medium-scale decoration with more floral arrangements.",
    images: [
      "https://i.ibb.co.com/93w0W4zR/FB-IMG-1773394787163-jpg.jpg",
      "https://i.ibb.co.com/fYb8Bnb0/Harshitaand-Sean-Engagement-Maha-Studios-Inc-1-jpg.jpg",
      "https://i.ibb.co.com/HDQ93Tcq/MPQ-Events-JPG-jpg.jpg",
      "https://i.ibb.co.com/Kjx9T0nH/Rakhi-Kumari-JPG-jpg.jpg",
      "https://i.ibb.co.com/G3GQ73y1/Reception-JPG-jpg.jpg",
      "https://i.ibb.co.com/LdycHzbS/Vidhi-Gohil-JPG-jpg.jpg",
      "https://i.ibb.co.com/QF7kYgz0/wedding-decor-JPG-jpg.jpg"
    ],
  },
  {
    id: "premium",
    name: "Premium Package",
    priceRange: "35k – 60k",
    description: "High-quality decoration with premium lighting and backdrop designs.",
    images: [
      "https://i.ibb.co.com/F4McXKHP/25037-jpg.jpg",
      "https://i.ibb.co.com/DPWLVJWv/25041-jpg.jpg",
      "https://i.ibb.co.com/MkNWYQh6/25045-jpg.jpg",
      "https://i.ibb.co.com/n8Q6jnV3/25048-jpg.jpg",
      "https://i.ibb.co.com/s9Yhzxqp/25050-jpg.jpg",
      "https://i.ibb.co.com/2w6RSfx/25052-jpg.jpg"
    ],
  },
  {
    id: "royal",
    name: "Royal Package",
    priceRange: "60k+",
    description: "Luxury decoration for grand events with exquisite details and grand stages.",
    images: [
      "https://i.ibb.co.com/yc0kdJFr/1510-jpg.jpg",
      "https://i.ibb.co.com/wN4KJbmD/3360-jpg.jpg",
      "https://i.ibb.co.com/CpkfwnXn/3641-jpg.jpg",
      "https://i.ibb.co.com/bkz21dB/8439-jpg.jpg",
      "https://i.ibb.co.com/cKVYPwPP/25063-jpg.jpg",
      "https://i.ibb.co.com/RpjnPVcZ/25065.png",
      "https://i.ibb.co.com/LzTwJg5Q/25067-jpg.jpg",
      "https://i.ibb.co.com/WNJS3xQk/25069-jpg.jpg",
      "https://i.ibb.co.com/q35hv3Bp/25073-jpg.jpg"
    ],
  },
];

const WeddingCarPackages = [
  {
    id: "basic",
    name: "Basic Package",
    priceRange: "10k – 15k",
    description: "Simple yet elegant decoration for intimate gatherings.",
    images: [
      "https://i.ibb.co.com/j9nzcsm6/download-30.jpg",
      "https://i.ibb.co.com/ZRHBb06c/Car-decoration-flower.jpg",
      "https://i.ibb.co.com/fzNQmyCt/Car-decor-idea.jpg",
      "https://i.ibb.co.com/0yZ7M4Lw/Babar-Flower-jpg.jpg",
      "https://i.ibb.co.com/7JB2nY2f/download-34.jpg",
      "https://i.ibb.co.com/N6dnxSC7/download-33.jpg",
      "https://i.ibb.co.com/qLkkjYsF/download-32.jpg",
      "https://i.ibb.co.com/p6sxnJx3/download-31.jpg",
      "https://i.ibb.co.com/JFvpGMq4/download-45.jpg",
      "https://i.ibb.co.com/KkWs917/download-44.jpg",
      "https://i.ibb.co.com/DHDL7VmZ/download-37.jpg",
      "https://i.ibb.co.com/S4xnt5pm/download-35.jpg",
      "https://i.ibb.co.com/WWt6g8kz/download-52.jpg",
      "https://i.ibb.co.com/Fbp6C5NF/download-50.jpg",
      "https://i.ibb.co.com/jsqGSqh/download-47.jpg",
      "https://i.ibb.co.com/v4McjxMB/download-46.jpg",
      "https://i.ibb.co.com/WWtdWkhv/7-Seater-Fortuner-One-Way-Taxi-on-Rent-in-Chandigarh-GTBTravels34.jpg",
      "https://i.ibb.co.com/bjS33CCZ/Wedding.jpg",
      "https://i.ibb.co.com/HpLfNyqJ/Wedding-Car-Decoration.jpg",
      "https://i.ibb.co.com/gb1FmWTj/Wedding-BMW-Car-on-Rent-in-Patna.jpg",
      "https://i.ibb.co.com/cc44m3xb/download-54.jpg",
      "https://i.ibb.co.com/WWt6g8kz/download-52.jpg"
    ],
  },
  {
    id: "standard",
    name: "Standard Package",
    priceRange: "15k – 35k",
    description: "Beautiful medium-scale decoration with more floral arrangements.",
    images: [
      "https://i.ibb.co.com/TB0KBkh6/download-48.jpg",
      "https://i.ibb.co.com/Q7gBmf3c/download-43.jpg",
      "https://i.ibb.co.com/C3GKWcw3/download-1-4.jpg",
      "https://i.ibb.co.com/cK5kyq8N/Celebrations25-Wedding-Wire2026-car-decorated.jpg",
      "https://i.ibb.co.com/ZpmghFhv/image.jpg",
      "https://i.ibb.co.com/wFkjs2vt/image.jpg",
      "https://i.ibb.co.com/ksXbhCp4/Tik-Tok-qaiserrajpoot88.jpg",
      "https://i.ibb.co.com/nqHdXsxM/malikchandigarhevent-malikchandigarhevent-Wedding-Decorator-Haldi-Mehndi-Decor-Engagement-Decoration.jpg",
      "https://i.ibb.co.com/cX1TDcjk/download-51.jpg",
      "https://i.ibb.co.com/cSWvR9wY/download-49.jpg"
    ],
  },
  {
    id: "premium",
    name: "Premium Package",
    priceRange: "35k – 60k",
    description: "High-quality decoration with premium lighting and backdrop designs.",
    images: [
      "https://i.ibb.co.com/d4H200sG/car-weeding-shadi.jpg",
      "https://i.ibb.co.com/4gP4T29f/Car.jpg",
      "https://i.ibb.co.com/9mMdPYdj/download-1-3.jpg",
      "https://i.ibb.co.com/6cXck75b/download-32-1.jpg",
      "https://i.ibb.co.com/hFtRqYJT/download-40.jpg",
      "https://i.ibb.co.com/ZpFcmnns/fashion-bridal-bridetobe-weddingphotographer-weddings-groom-engagement-party-like-instagood.jpg",
      "https://i.ibb.co.com/Cp2bX5wk/Wedding-car-decoration-1.jpg",
      "https://i.ibb.co.com/LhPTcnTW/White-wedding-Car.jpg",
      "https://i.ibb.co.com/4CCgyJH/image.jpg",
      "https://i.ibb.co.com/hF2Sk5Cs/20-Best-Wedding-Car-Decoration-Ideas-In-India-2026.jpg"
    ],
  },
  {
    id: "royal",
    name: "Royal Package",
    priceRange: "60k+",
    description: "Luxury decoration for grand events with exquisite details and grand stages.",
    images: [
      "https://i.ibb.co.com/R4ZpVKqY/download-31-1.jpg",
      "https://i.ibb.co.com/cSKyVKkx/download-33-1.jpg",
      "https://i.ibb.co.com/fdswQdm0/download-34-1.jpg",
      "https://i.ibb.co.com/whq8f0Xv/download-35-1.jpg",
      "https://i.ibb.co.com/NdgHKqdW/download-36.jpg",
      "https://i.ibb.co.com/pjWbq5qd/download-38.jpg",
      "https://i.ibb.co.com/5gXHTVdP/download-39.jpg",
      "https://i.ibb.co.com/5Xy0ST06/car-Decoration.jpg",
      "https://i.ibb.co.com/39KhxqDT/Celebrations25-Wedding-Wire2026-car-decorated-1.jpg",
      "https://i.ibb.co.com/N2W6cKtK/download-30-1.jpg"
    ],
  },
];

const HaldiCeremonyPackages = [
  {
    id: "basic",
    name: "Basic Package",
    priceRange: "10k – 15k",
    description: "Simple yet elegant decoration for intimate gatherings.",
    images: [
      "https://i.ibb.co.com/gbKqjcbs/10251-jpg.jpg",
      "https://i.ibb.co.com/twgZxpN2/22780-jpg.jpg",
      "https://i.ibb.co.com/Tq4ggptH/22783-jpg.jpg",
      "https://i.ibb.co.com/kgPqFb9D/22786-jpg.jpg",
      "https://i.ibb.co.com/j99qpBj4/22791-jpg.jpg",
      "https://i.ibb.co.com/kVr28RJ5/22792-jpg.jpg"
    ],
  },
  {
    id: "standard",
    name: "Standard Package",
    priceRange: "15k – 35k",
    description: "Beautiful medium-scale decoration with more floral arrangements.",
    images: [
      "https://i.ibb.co.com/YBr4QFXJ/3947-jpg.jpg",
      "https://i.ibb.co.com/SDTWJNSK/22415-jpg.jpg",
      "https://i.ibb.co.com/mVN6PNMY/22452-jpg.jpg",
      "https://i.ibb.co.com/fY8mCgKX/22421-jpg.jpg",
      "https://i.ibb.co.com/nqYc39Tw/22782-jpg.jpg",
      "https://i.ibb.co.com/kgZg01Bt/22463-jpg.jpg",
      "https://i.ibb.co.com/gFz4N0TK/22787-jpg.jpg",
      "https://i.ibb.co.com/pjDvKXVN/22784-jpg.jpg",
      "https://i.ibb.co.com/4g4khd2V/22790-jpg.jpg",
      "https://i.ibb.co.com/fYL9J3nQ/22788-jpg.jpg"
    ],
  },
  {
    id: "premium",
    name: "Premium Package",
    priceRange: "35k – 60k",
    description: "High-quality decoration with premium lighting and backdrop designs.",
    images: [
      "https://i.ibb.co.com/zhDRWzTx/25268-jpg.jpg",
      "https://i.ibb.co.com/4R2xTdCH/25266-jpg.jpg",
      "https://i.ibb.co.com/Lzm77j7k/25264-jpg.jpg",
      "https://i.ibb.co.com/B5ypKFwZ/25262-jpg.jpg",
      "https://i.ibb.co.com/PvbFjFw4/25286-jpg.jpg",
      "https://i.ibb.co.com/dwfz86vb/25276-jpg.jpg",
      "https://i.ibb.co.com/nMhS6HCB/25272-jpg.jpg",
      "https://i.ibb.co.com/YFsb87jD/25270-jpg.jpg"
    ],
  },
  {
    id: "royal",
    name: "Royal Package",
    priceRange: "60k+",
    description: "Luxury decoration for grand events with exquisite details and grand stages.",
    images: [
      "https://i.ibb.co.com/r2xZgmWM/17033-jpg.jpg",
      "https://i.ibb.co.com/cSRHWMrn/15868-jpg.jpg",
      "https://i.ibb.co.com/20RF990c/7945-jpg.jpg",
      "https://i.ibb.co.com/CswVwkPw/5455-jpg.jpg",
      "https://i.ibb.co.com/67ZVMJC1/22779-jpg.jpg",
      "https://i.ibb.co.com/NgB8yvgS/22467-jpg.jpg",
      "https://i.ibb.co.com/kgmycHry/22424-jpg.jpg",
      "https://i.ibb.co.com/DPw0TNz8/22116-jpg.jpg",
      "https://i.ibb.co.com/GfMR1Spr/23376-jpg.jpg",
      "https://i.ibb.co.com/Y7tR97HG/23238-jpg.jpg",
      "https://i.ibb.co.com/TDrHdtwh/23187-jpg.jpg",
      "https://i.ibb.co.com/wx9JZF5/23177-jpg.jpg",
      "https://i.ibb.co.com/n8n4TxzD/24537-jpg.jpg",
      "https://i.ibb.co.com/35W4PpmL/23861-jpg.jpg",
      "https://i.ibb.co.com/SbHfNrc/23849-jpg.jpg",
      "https://i.ibb.co.com/8grYRtYs/23848-jpg.jpg",
      "https://i.ibb.co.com/cXbyphHw/24562-jpg.jpg",
      "https://i.ibb.co.com/7JBgYCpz/24548-jpg.jpg"
    ],
  },
];

const WeddingNightRoomPackages = [
  {
    id: "basic",
    name: "Basic Package",
    priceRange: "10k – 15k",
    description: "Simple yet elegant decoration for intimate gatherings.",
    images: [
      "https://i.ibb.co.com/chnQDQxN/25362-jpg.jpg",
      "https://i.ibb.co.com/Tx1J9PQK/25360-jpg.jpg",
      "https://i.ibb.co.com/8DRD98Hf/25358-jpg.jpg",
      "https://i.ibb.co.com/2m44nyv/25356-jpg.jpg",
      "https://i.ibb.co.com/7NLCTBH2/25368-jpg.jpg",
      "https://i.ibb.co.com/hJPH3M7T/25366-jpg.jpg",
      "https://i.ibb.co.com/20L5xYSh/25364-jpg.jpg"
    ],
  },
  {
    id: "standard",
    name: "Standard Package",
    priceRange: "15k – 35k",
    description: "Beautiful medium-scale decoration with more floral arrangements.",
    images: [
      "https://i.ibb.co.com/TMCqsTLs/download-1.jpg",
      "https://i.ibb.co.com/6cDFpmzz/download-26.jpg",
      "https://i.ibb.co.com/ym3tcb0B/download-25.jpg",
      "https://i.ibb.co.com/67bpjp1F/download-12.jpg",
      "https://i.ibb.co.com/YT3Z5zdL/download-2.jpg",
      "https://i.ibb.co.com/RkngJfmL/image.jpg",
      "https://i.ibb.co.com/Swh8HzsM/Teen-Girl-Royalty-16-Magical-Princess-Bedroom-Inspirations-Straight-Out-Of-A-Fairytale-Home-Decor.jpg",
      "https://i.ibb.co.com/G4Y0dNSt/Romantic-Canopy-Bedroom-Decor-Elegant-Boho-Bedroom-with-Floral-Drapes.jpg",
      "https://i.ibb.co.com/hJ9kMKrw/download.jpg",
      "https://i.ibb.co.com/4gwddbc9/download-27.jpg"
    ],
  },
  {
    id: "premium",
    name: "Premium Package",
    priceRange: "35k – 60k",
    description: "High-quality decoration with premium lighting and backdrop designs.",
    images: [
      "https://i.ibb.co.com/QFt4X470/Celebrations25-Wedding-Wire2026-romantic-bedroom-1.jpg",
      "https://i.ibb.co.com/mFDpHYDm/Celebrations25-Wedding-Wire2026-1.jpg",
      "https://i.ibb.co.com/d0xggGNR/Bedroom-Decoration-Ideas-Wedding.jpg",
      "https://i.ibb.co.com/60ck0HRg/Cozy-Room-Cozy-Lifestyle-Room-Aesthetic-Pinterest-Room-Bedroom-Decor-Cozy-Vibes-Home-Decor-Ideas-A.jpg",
      "https://i.ibb.co.com/20V5x3QG/Sasta-decore.jpg",
      "https://i.ibb.co.com/zhm84vFR/Elegant-Bedroom-Design-Ideas.jpg",
      "https://i.ibb.co.com/LdsrRhSj/download-29.jpg",
      "https://i.ibb.co.com/Rkn1wGP2/download-3.jpg",
      "https://i.ibb.co.com/C3LwztBB/download-2-1.jpg",
      "https://i.ibb.co.com/W4gFrmhr/download-1-1.jpg"
    ],
  },
  {
    id: "royal",
    name: "Royal Package",
    priceRange: "60k+",
    description: "Luxury decoration for grand events with exquisite details and grand stages.",
    images: [
      "https://i.ibb.co.com/bjpZybFL/download-1-2.jpg",
      "https://i.ibb.co.com/sphWX9zJ/8641-jpg.jpg",
      "https://i.ibb.co.com/Gq6W9rk/22-Chic-Bedroom-Ideas-to-Embrace-a-Soft-Country-Aesthetic-with-Flower-Decor.jpg",
      "https://i.ibb.co.com/846RR6GM/20-Romantic-Wedding-Room-Decoration-Ideas-2024.jpg",
      "https://i.ibb.co.com/Z1Rq5VSQ/download-27-1.jpg",
      "https://i.ibb.co.com/67mhcvmv/download-25-1.jpg",
      "https://i.ibb.co.com/x8M9vYg5/download-4.jpg",
      "https://i.ibb.co.com/mV7JBfyj/download-2-2.jpg",
      "https://i.ibb.co.com/Q7fbJhx3/Stunning-Flower-Arrangements-That-Instantly-Brighten-Any-Room.jpg",
      "https://i.ibb.co.com/pvHyPbHd/romantic-1-bedroom-jpg.jpg",
      "https://i.ibb.co.com/CppcBXqZ/Hyderabad-flower-decor-Bed-decor-for-first-night-with-roses-baby-breathe.jpg"
    ],
  },
];

const WeddingStagePackages = [
  {
    id: "basic",
    name: "Basic Package",
    priceRange: "10k – 15k",
    description: "Simple yet elegant decoration for intimate gatherings.",
    images: [
      "https://i.ibb.co.com/jk55CKdn/25189-jpg-1.jpg",
      "https://i.ibb.co.com/NdQrc91V/25191-jpg-1.jpg",
      "https://i.ibb.co.com/v6hhW6kK/25195-jpg-1.jpg",
      "https://i.ibb.co.com/ZzD3z6WJ/25197-jpg-1.jpg",
      "https://i.ibb.co.com/dJM1sLSY/25199-jpg-1.jpg",
      "https://i.ibb.co.com/m5bSWt0v/25201-jpg-1.jpg",
      "https://i.ibb.co.com/ksxQLmQh/25203-jpg-1.jpg",
      "https://i.ibb.co.com/9m1Y9hg1/25205-jpg-2.jpg",
      "https://i.ibb.co.com/mVt4zPqK/25208-jpg-1.jpg",
      "https://i.ibb.co.com/Mx6Fw7nz/25210-jpg-1.jpg",
      "https://i.ibb.co.com/k2ZcHmTh/25175-jpg-1.jpg",
      "https://i.ibb.co.com/LX1Z4X4w/25177-jpg-1.jpg",
      "https://i.ibb.co.com/LDXhqwcs/25179-jpg-1.jpg",
      "https://i.ibb.co.com/PGLDpgH2/25181-jpg-1.jpg",
      "https://i.ibb.co.com/MxJ5wm9T/25183-jpg-1.jpg",
      "https://i.ibb.co.com/m5sqg3Sq/25185-jpg-1.jpg",
      "https://i.ibb.co.com/jPVScbsp/Consuelo-Hernandez-JPG-jpg.jpg"
    ],
  },
  // {
  //   id: "standard",
  //   name: "Standard Package",
  //   priceRange: "15k – 35k",
  //   description: "Beautiful medium-scale decoration with more floral arrangements.",
  //   images: Array.from({ length: 9 }, (_, i) => `https://picsum.photos/seed/weddingstage-standard-${i}/800/600`),
  // },
  {
    id: "premium",
    name: "Premium Package",
    priceRange: "35k – 60k",
    description: "High-quality decoration with premium lighting and backdrop designs.",
    images: [
      "https://i.ibb.co.com/HpYWGh2c/25090-jpg.jpg",
      "https://i.ibb.co.com/Wp6mqdwT/25092-jpg.jpg",
      "https://i.ibb.co.com/MxgKYQq2/25094-jpg.jpg",
      "https://i.ibb.co.com/yn34Mmyd/25096-jpg.jpg",
      "https://i.ibb.co.com/fVq1SqXw/25098-jpg.jpg",
      "https://i.ibb.co.com/p6NXjLFC/25100-jpg.jpg",
      "https://i.ibb.co.com/w2pgQcS/25102-jpg.jpg",
      "https://i.ibb.co.com/7xZxtYXC/25104-jpg.jpg",
      "https://i.ibb.co.com/Xxf6YQ09/25106-jpg.jpg",
      "https://i.ibb.co.com/SwSDcQCS/25108-jpg.jpg",
      "https://i.ibb.co.com/TxVcdBLH/1511-jpg.jpg",
      "https://i.ibb.co.com/XxtzZ0K9/3996-jpg.jpg",
      "https://i.ibb.co.com/mrTsmVyZ/7883-jpg.jpg",
      "https://i.ibb.co.com/bMJ0QMG5/23196-jpg.jpg",
      "https://i.ibb.co.com/QvQ2vr75/24536-jpg.jpg",
      "https://i.ibb.co.com/0jt0X6j2/24566-jpg.jpg",
      "https://i.ibb.co.com/TBzvMDpP/25088-jpg.jpg"
    ],
  },
  {
    id: "royal",
    name: "Royal Package",
    priceRange: "60k+",
    description: "Luxury decoration for grand events with exquisite details and grand stages.",
    images: [
      "https://i.ibb.co.com/PsZv6pv2/24534-jpg.jpg",
      "https://i.ibb.co.com/yFLmdqWK/24541-jpg.jpg",
      "https://i.ibb.co.com/VW4WwCHr/24542-jpg.jpg",
      "https://i.ibb.co.com/1JfgmLC2/24544-jpg.jpg",
      "https://i.ibb.co.com/N2D917PT/24550-jpg.jpg",
      "https://i.ibb.co.com/jktmzvWX/24551-jpg.jpg",
      "https://i.ibb.co.com/9xbsQ7q/24557-jpg.jpg",
      "https://i.ibb.co.com/WWrmz6rb/24558-jpg.jpg",
      "https://i.ibb.co.com/b4P0wdx/24559-jpg.jpg",
      "https://i.ibb.co.com/8gqgsVM6/24561-jpg.jpg",
      "https://i.ibb.co.com/N6qCnG09/24565-jpg.jpg",
      "https://i.ibb.co.com/k68M20s6/3662-jpg.jpg",
      "https://i.ibb.co.com/bkz21dB/8439-jpg.jpg",
      "https://i.ibb.co.com/mpscypm/15174-jpg.jpg",
      "https://i.ibb.co.com/tTgk6r1c/22111-jpg.jpg",
      "https://i.ibb.co.com/ycDLPQCZ/22113-jpg.jpg",
      "https://i.ibb.co.com/9k39Fvj4/22114-jpg.jpg",
      "https://i.ibb.co.com/W4GNr9Nv/22118-jpg.jpg",
      "https://i.ibb.co.com/tTDmcxHC/22120-jpg.jpg",
      "https://i.ibb.co.com/VWdZhLTm/22732-jpg.jpg",
      "https://i.ibb.co.com/gbzFC7SG/23174-jpg.jpg",
      "https://i.ibb.co.com/xWnJy3P/23175-jpg.jpg",
      "https://i.ibb.co.com/PvnDmDtK/23180-jpg.jpg",
      "https://i.ibb.co.com/cnBv8Nv/23184-jpg.jpg",
      "https://i.ibb.co.com/844v0nMF/23197-jpg.jpg",
      "https://i.ibb.co.com/PG4vfNQc/23205-jpg.jpg",
      "https://i.ibb.co.com/wrPSyy6z/23209-jpg.jpg",
      "https://i.ibb.co.com/TDG1VdgR/23257-jpg.jpg",
      "https://i.ibb.co.com/bjRwKNzG/23845-jpg.jpg",
      "https://i.ibb.co.com/n8w6SH5K/23863-jpg.jpg",
      "https://i.ibb.co.com/twF3NRvw/23865-jpg.jpg",
      "https://i.ibb.co.com/TxW39fHB/23870-jpg.jpg",
      "https://i.ibb.co.com/qYhqVNK5/24528-jpg.jpg",
      "https://i.ibb.co.com/cH1WNvg/24529-jpg.jpg",
      "https://i.ibb.co.com/CpkfwnXn/3641-jpg.jpg",
      "https://i.ibb.co.com/FL5xCJJx/1510-jpg.jpg",
      "https://i.ibb.co.com/wN4KJbmD/3360-jpg.jpg"
    ],
  },
];

const WeddingGatePackages = [
  {
    id: "basic",
    name: "Basic Package",
    priceRange: "10k – 15k",
    description: "Simple yet elegant decoration for intimate gatherings.",
    images: [
      "https://i.ibb.co.com/Z68dy0Kw/Any-Conv-com-download-2.jpg",
      "https://i.ibb.co.com/XxFYtqW7/Any-Conv-com-download-25.jpg",
      "https://i.ibb.co.com/RTjsGWQL/Any-Conv-com-download-26.jpg",
      "https://i.ibb.co.com/nNc28c0r/Any-Conv-com-download.jpg",
      "https://i.ibb.co.com/B2DFg8dm/Any-Conv-com-Glam.jpg",
      "https://i.ibb.co.com/4wcNCKCY/Any-Conv-com-Pink-wedding-luxealtars-1.jpg",
      "https://i.ibb.co.com/PdYyH1L/Any-Conv-com-The-arch-from-my-wedding-It-was-so-gorgeous.jpg",
      "https://i.ibb.co.com/fY6D2pKg/Any-Conv-com-Decor-exterior-nunta.jpg",
      "https://i.ibb.co.com/4ZQXWM91/Any-Conv-com-Decoraci-n-con-luces.jpg",
      "https://i.ibb.co.com/7xHsG2Rw/Any-Conv-com-download-1.jpg"
    ],
  },
  {
    id: "standard",
    name: "Standard Package",
    priceRange: "15k – 35k",
    description: "Beautiful medium-scale decoration with more floral arrangements.",
    images: [
      "https://i.ibb.co.com/R4bV40m5/Any-Conv-com-download-27.jpg",
      "https://i.ibb.co.com/278BRRQ8/Any-Conv-com-download-28.jpg",
      "https://i.ibb.co.com/HDKYK58r/Any-Conv-com-download-29.jpg",
      "https://i.ibb.co.com/ymC5RGm3/Any-Conv-com-download-30.jpg",
      "https://i.ibb.co.com/BSQXm9t/Any-Conv-com-Entry-Decoration-simple-entry-decoration-engagement-ceremony-entry-decoration.jpg",
      "https://i.ibb.co.com/rGDxdgzw/Any-Conv-com-Entry.jpg",
      "https://i.ibb.co.com/Kz3jV4vS/Any-Conv-com-Fresh-Ideas-for-Decorating-Wedding-Tents-Soft-Soulful.jpg",
      "https://i.ibb.co.com/fdL8P4nn/Any-Conv-com-Pastel-Entrance-Arch-for-Your-Wedding.jpg",
      "https://i.ibb.co.com/tpFYhv37/Any-Conv-com-Stockton-Golf-Country-Club-first-tee-ceremony-Briggs-Photography.jpg",
      "https://i.ibb.co.com/KzDDFtrG/Any-Conv-com-Wedding-arch-design.jpg",
      "https://i.ibb.co.com/KxbZ5zQc/Any-Conv-com.jpg",
      "https://i.ibb.co.com/4wsxWv0k/Any-Conv-com-15-Wedding-Entrance-Decor-Ideas-to-Wow-Your-Guests.jpg",
      "https://i.ibb.co.com/7tfbx1c5/Any-Conv-com-85-Outdoor-Wedding-Arch-Ideas-for-a-Picture-Perfect-Ceremony.jpg",
      "https://i.ibb.co.com/twLT6csQ/Any-Conv-com-Artificial-flowers-entry-gate-surat-balloon-flower-decoration-Sandeep-Sharma-M-814.jpg",
      "https://i.ibb.co.com/DP8FBxr5/Any-Conv-com-Church-decor.jpg",
      "https://i.ibb.co.com/Fk20LftR/Any-Conv-com-download-1-1.jpg",
      "https://i.ibb.co.com/Zz5WxnmQ/Any-Conv-com-download-2-1.jpg",
      "https://i.ibb.co.com/MDY4P0Yj/Any-Conv-com-download-26-1.jpg"
    ],
  },
  {
    id: "premium",
    name: "Premium Package",
    priceRange: "35k – 60k",
    description: "High-quality decoration with premium lighting and backdrop designs.",
    images: [
      "https://i.ibb.co.com/GvZzpqLM/Any-Conv-com-Pathway-Decoration-using-white-orange-clothes-and-flowers.jpg",
      "https://i.ibb.co.com/62dVnSh/Any-Conv-com-Pink-roses-How-about-white-roses-Maybe-a-blush-one-or-two-We-ll-take-em-all.jpg",
      "https://i.ibb.co.com/wrspRGn0/Any-Conv-com-Romantic-Wedding-Theme-Ideas-for-2025-Brides.jpg",
      "https://i.ibb.co.com/W456xQjQ/Any-Conv-com-Royal-Blue-Chiffon-Fabric-Drapery-for-Wedding-Arch-20-Ft-Chiffon-for-Wedding-Backdrop-C.jpg",
      "https://i.ibb.co.com/SCgXcYG/Any-Conv-com-Simple-beautiful-floral-decor.jpg",
      "https://i.ibb.co.com/h11rCGMx/Any-Conv-com-Such-gorgeous-shades-of-baby-pink-and-the-violet-colors-We-are-loving-this-intimate.jpg",
      "https://i.ibb.co.com/NnnhS1MM/Any-Conv-com-Transform-Your-Celebration-with-the-Best-Wedding-Venues.jpg",
      "https://i.ibb.co.com/cSDFDTR1/Any-Conv-com-Transform-Your-Wedding-with-a-Rococo-Forest-Theme.jpg",
      "https://i.ibb.co.com/MyRy0qRW/Any-Conv-com-wedding-aesthetic.jpg",
      "https://i.ibb.co.com/fzjQgrj4/Any-Conv-com-Yellow-Entrance-Arch.jpg",
      "https://i.ibb.co.com/7xq4q1yr/Any-Conv-com-2-Post-Wooden-Arch.jpg",
      "https://i.ibb.co.com/HTVwfg1y/Any-Conv-com-19-Quincea-era-Decorations-Ideas-That-Feel-Royal.jpg",
      "https://i.ibb.co.com/k24qRxYc/Any-Conv-com-85-Outdoor-Wedding-Arch-Ideas-for-a-Picture-Perfect-Ceremony-1.jpg",
      "https://i.ibb.co.com/HvBC496/Any-Conv-com-Backdrop-Ideas.jpg",
      "https://i.ibb.co.com/ymTZ7xQH/Any-Conv-com-Dise-os-exclusivas-de-matrimonio-con-encanto-en-moda-de-ideas-de-boda.jpg",
      "https://i.ibb.co.com/CKLnsG6S/Any-Conv-com-download-1-2.jpg",
      "https://i.ibb.co.com/MDCVP5VW/Any-Conv-com-download-2-2.jpg",
      "https://i.ibb.co.com/35hYgtX5/Any-Conv-com-download-3.jpg",
      "https://i.ibb.co.com/CKBv2cKP/Any-Conv-com-download-26-2.jpg",
      "https://i.ibb.co.com/6c7WrwYY/Any-Conv-com-download-27-1.jpg",
      "https://i.ibb.co.com/HDX3Pc7N/Any-Conv-com-download-28-1.jpg",
      "https://i.ibb.co.com/pvf4WwkL/Any-Conv-com-download-29-1.jpg",
      "https://i.ibb.co.com/gLWyMmtF/Any-Conv-com-download-30-1.jpg",
      "https://i.ibb.co.com/kgzLxwqR/Any-Conv-com-download-31.jpg",
      "https://i.ibb.co.com/PsH3BRZx/Any-Conv-com-download-32.jpg",
      "https://i.ibb.co.com/Kj1pgpDr/Any-Conv-com-download-33.jpg",
      "https://i.ibb.co.com/twhrS9t1/Any-Conv-com-Dreamy-entrance-backdrop-for-your-wedding.jpg",
      "https://i.ibb.co.com/dsrC2NYv/Any-Conv-com-Dreamy-Outdoor-Wedding-Arch-Inspiration-Romantic-Lakeside-Ceremony.jpg",
      "https://i.ibb.co.com/6c6Z0r3c/Any-Conv-com-Dreamy-Wedding-Flower-Decorations.jpg"
    ],
  },
  {
    id: "royal",
    name: "Royal Package",
    priceRange: "60k+",
    description: "Luxury decoration for grand events with exquisite details and grand stages.",
    images: [
      "https://i.ibb.co.com/Pz4rvBcW/Destination-Wedding-Dreams-Plan-Your-Perfect-Day.jpg",
      "https://i.ibb.co.com/FLZHjKWL/download-31-2.jpg",
      "https://i.ibb.co.com/DDL3TCpF/download-35-2.jpg",
      "https://i.ibb.co.com/7JKVdvc1/Fairy-Tale-Wedding-with-Flower-Arches-and-Floating-Lanterns.jpg",
      "https://i.ibb.co.com/sJJxvfDY/Free-Enchanting-Night-Wedding-A-Floral-Arch-Adorned-with-Fairy-Lights.jpg",
      "https://i.ibb.co.com/6GM5cRM/Elegant-Wedding-Inspiration.jpg",
      "https://i.ibb.co.com/sp2c8QsV/15-Wedding-Entrance-Decor-Ideas-to-Wow-Your-Guests-Instantly.jpg",
      "https://i.ibb.co.com/RG07nNj6/23-Romantic-Wedding-Arch-Ideas-to-Make-Your-Ceremony-Absolutely-Magical.jpg",
      "https://i.ibb.co.com/BVRXjqtd/3923-jpg.jpg",
      "https://i.ibb.co.com/RTXVtgNH/3928-jpg.jpg",
      "https://i.ibb.co.com/4QFqL5h/3932-jpg.jpg",
      "https://i.ibb.co.com/G40QygjC/3960-jpg.jpg"
    ],
  },
];

const MehediStagePackages = [
  {
    id: "basic",
    name: "Basic Mehedi Stage",
    priceRange: "8k – 12k",
    description: "Simple Mehedi stage decoration with basic floral and fabric backdrop.",
    images: [
      "https://i.ibb.co.com/C5cLfmXk/mehedi-besic-4.jpg",
      "https://i.ibb.co.com/SDQNyBhV/mehedi-besic-5.jpg",
      "https://i.ibb.co.com/tpbD6DfQ/mehedi-besic-3.jpg",
      "https://i.ibb.co.com/ZsPmfWt/mehedi-besic-2.jpg",
      "https://i.ibb.co.com/VYJ6RXZh/mehedi-besic-1.jpg"
    ],
  },
  {
    id: "standard",
    name: "Standard Mehedi Stage",
    priceRange: "12k – 25k",
    description: "Colorful Mehedi stage with floral decorations, lights, and elegant seating.",
    images: [
      "https://i.ibb.co.com/CK3d83M9/mehedi-standard-3.jpg",
      "https://i.ibb.co.com/zWQGnVfH/mehedi-standard-1.jpg",
      "https://i.ibb.co.com/wN1RsyD8/mehedi-standard-2.jpg",
      "https://i.ibb.co.com/21X28jVZ/mehedi-standard-5.jpg",
      "https://i.ibb.co.com/wZnZ8Kwv/mehedi-standard-4.jpg"
    ],
  },
  {
    id: "premium",
    name: "Premium Mehedi Stage",
    priceRange: "25k – 45k",
    description: "Premium Mehedi stage with vibrant colors, flower canopy, and designer backdrop.",
    images: [
      "https://i.ibb.co.com/2zVx42g/mehedi-premi-5.png",
      "https://i.ibb.co.com/tM7gnzpt/mehedi-premi-2.jpg",
      "https://i.ibb.co.com/wrbQjQPW/mehedi-premi-3.jpg",
      "https://i.ibb.co.com/21pwWV4Y/mehedi-premi-4.jpg",
      "https://i.ibb.co.com/mVwFDzQm/mehedi-premi-1.jpg"
    ],
  },
  {
    id: "royal",
    name: "Royal Mehedi Stage",
    priceRange: "45k+",
    description: "Grand Mehedi stage with luxury seating, heavy floral work, and premium lighting.",
    images: [
      "https://i.ibb.co.com/45mPPqS/mehedi-royel-4.jpg",
      "https://i.ibb.co.com/1YvPPGYt/mehedi-royel-1.jpg",
      "https://i.ibb.co.com/TBMZ7nP8/mehedi-royel-2.jpg",
      "https://i.ibb.co.com/JWnK5NNR/mehedi-royel-3.jpg",
      "https://i.ibb.co.com/5XwD0tG3/mehedi-royel-5.jpg"
    ],
  },
];

export const SERVICES: Service[] = [
  {
    id: "haldi",
    title: "Haldi Ceremony Decoration",
    banglaTitle: "হলদি অনুষ্ঠান সজ্জা",
    description: "Vibrant yellow-themed decorations for your traditional Haldi ceremony.",
    image: "https://i.ibb.co.com/n8n4TxzD/24537-jpg.jpg",
    images: ["https://picsum.photos/seed/haldi/800/600"],
    packages: HaldiCeremonyPackages,
  },
  {
    id: "mehndi",
    title: "Mehndi Ceremony Decoration",
    banglaTitle: "মেহেদি অনুষ্ঠান সজ্জা",
    description: "Creative and colorful setups for a memorable Mehndi night.",
    image: "https://i.ibb.co.com/hJ1kkfnr/9b32301106b3d2b7b9fbb7149bfc167d-1.jpg",
    images: ["https://i.ibb.co.com/GfMR1Spr/23376-jpg.jpg", "https://i.ibb.co.com/pBMWRFVh/7894-jpg.jpg"],
    packages: MehediStagePackages,
  },


  {
    id: "wedding-stage",
    title: "Wedding Stage Decoration",
    banglaTitle: "বিয়ের স্টেজ ডেকোরেশন",
    description: "Grand and elegant stage designs for your big day.",
    image: "https://i.ibb.co.com/n8w6SH5K/23863-jpg.jpg",
    images: ["https://picsum.photos/seed/wedding/800/600"],
    packages: WeddingStagePackages,
  },
  {
    id: "reception-stage",
    title: "Wedding Reception Stage Decoration",
    banglaTitle: "বিয়ের রিসেপশন স্টেজ ডেকোরেশন",
    description: "Sophisticated and modern reception stage setups.",
    image: "https://i.ibb.co.com/99mQZQTm/bor-3.jpg",
    images: [
      "https://i.ibb.co.com/ycDLPQCZ/22113-jpg.jpg",
      "https://i.ibb.co.com/W4GNr9Nv/22118-jpg.jpg",
      "https://i.ibb.co.com/VWdZhLTm/22732-jpg.jpg",
      "https://i.ibb.co.com/gbzFC7SG/23174-jpg.jpg",
      "https://i.ibb.co.com/xWnJy3P/23175-jpg.jpg",
      "https://i.ibb.co.com/PvnDmDtK/23180-jpg.jpg",
      "https://i.ibb.co.com/cnBv8Nv/23184-jpg.jpg",
      "https://i.ibb.co.com/844v0nMF/23197-jpg.jpg",
      "https://i.ibb.co.com/PG4vfNQc/23205-jpg.jpg",
      "https://i.ibb.co.com/TDG1VdgR/23257-jpg.jpg",
      "https://i.ibb.co.com/qYhqVNK5/24528-jpg.jpg",
      "https://i.ibb.co.com/cH1WNvg/24529-jpg.jpg",
      "https://i.ibb.co.com/PsZv6pv2/24534-jpg.jpg",
      "https://i.ibb.co.com/N2D917PT/24550-jpg.jpg",
      "https://i.ibb.co.com/jktmzvWX/24551-jpg.jpg",
      "https://i.ibb.co.com/9xbsQ7q/24557-jpg.jpg",
      "https://i.ibb.co.com/WWrmz6rb/24558-jpg.jpg",
      "https://i.ibb.co.com/b4P0wdx/24559-jpg.jpg",
      "https://i.ibb.co.com/8gqgsVM6/24561-jpg.jpg",
      "https://i.ibb.co.com/N6qCnG09/24565-jpg.jpg",
      "https://i.ibb.co.com/FL5xCJJx/1510-jpg.jpg",
      "https://i.ibb.co.com/wN4KJbmD/3360-jpg.jpg",
      "https://i.ibb.co.com/CpkfwnXn/3641-jpg.jpg",
      "https://i.ibb.co.com/bkz21dB/8439-jpg.jpg",
      "https://i.ibb.co.com/mpscypm/15174-jpg.jpg",
      "https://i.ibb.co.com/tTgk6r1c/22111-jpg.jpg"
    ],
    packages: [],
  },
  {
    id: "birthday",
    title: "Birthday Stage Decoration",
    banglaTitle: "জন্মদিনের স্টেজ ডেকোরেশন",
    description: "Fun and themed decorations for all ages.",
    image: "https://i.ibb.co.com/7xCHK4PL/bor-1.jpg",
    images: [
      "https://i.ibb.co.com/Z1TdvVC5/7935-jpg.jpg",
      "https://i.ibb.co.com/ymnQz4Xq/7936-jpg.jpg",
      "https://i.ibb.co.com/Z1M19r20/7937-jpg.jpg",
      "https://i.ibb.co.com/LDG2h5bf/17034-jpg.jpg",
      "https://i.ibb.co.com/PvVPRw3T/3921-jpg.jpg",
      "https://i.ibb.co.com/PZymtwHp/7934-jpg.jpg"
    ],
    packages: [],
  },
  {
    id: "engagement",
    title: "Engagement Ceremony Stage Decoration",
    banglaTitle: "এঙ্গেজমেন্ট অনুষ্ঠানের স্টেজ ডেকোরেশন",
    description: "Romantic and classy setups for your engagement.",
    image: "https://i.ibb.co.com/yc0kdJFr/1510-jpg.jpg",
    images: ["https://picsum.photos/seed/engagement/800/600"],
    packages: EngagementCeremonyPackages,
  },
  {
    id: "islamic-mahfil",
    title: "Islamic Mahfil Stage Decoration",
    banglaTitle: "ইসলামিক মহফিল স্টেজ ডেকোরেশন",
    description: "Respectful and beautiful arrangements for religious gatherings.",
    image: "https://i.ibb.co.com/Y7kfsYPV/mahfil-9.jpg",
    images: [
      "https://i.ibb.co.com/3yhVSC28/mahfil-6.jpg",
      "https://i.ibb.co.com/cdM3q7n/mahfil-7.jpg",
      "https://i.ibb.co.com/FLnxyMQn/mahfil-2.jpg",
      "https://i.ibb.co.com/kVwjH0P4/mahfil-3.jpg",
      "https://i.ibb.co.com/bjG8b0FS/mahfil-4.jpg",
      "https://i.ibb.co.com/B21QkmtG/mahfil-5.jpg",
      "https://i.ibb.co.com/0yw0mqVj/mahfil-10.jpg",
      "https://i.ibb.co.com/1G3Y92jg/mahfil-8.jpg",
      "https://i.ibb.co.com/Y7kfsYPV/mahfil-9.jpg",
      "https://i.ibb.co.com/wFMTQVM7/mahfil-1.jpg"
    ],
    packages: [],
  },
  {
    id: "building-lighting-stage-decoration",
    title: "Building Lighting Stage Decoration",
    banglaTitle: "বিল্ডিং লাইটিং স্টেজ ডেকোরেশন",
    description: "Beautiful lighting decoration for buildings and stages, creating a stunning and festive atmosphere for weddings and special events.",
    image: "https://i.ibb.co.com/jZTnDCVT/decoration-lighting-service-330-1.jpg",
    images: [
      "https://i.ibb.co.com/HfxvPSzB/download-29-2.jpg",
      "https://i.ibb.co.com/s9c584DJ/My-Sweet-Home.jpg",
      "https://i.ibb.co.com/rKGCqSFC/Farm-house.jpg",
      "https://i.ibb.co.com/PzD7Ghky/Entrance-gate-decorations-for-sangeet.jpg",
      "https://i.ibb.co.com/LDMhXRTc/download-41.jpg",
      "https://i.ibb.co.com/391ckLgc/download-40-1.jpg",
      "https://i.ibb.co.com/PZLqNVYZ/download-36-2.jpg",
      "https://i.ibb.co.com/PGFjtkDD/download-35-4.jpg",
      "https://i.ibb.co.com/v4FhLW4g/download-34-3.jpg",
      "https://i.ibb.co.com/S4sJ5RvD/download-33-3.jpg",
      "https://i.ibb.co.com/Q5XfRtY/download-32-3.jpg",
      "https://i.ibb.co.com/Kj0J7HQG/download-30-3.jpg",
      "https://i.ibb.co.com/NvYDzn3/download-31-4.jpg"
    ],
    packages: [],
  },
  {
    id: "baby-shower",
    title: "Baby Shower Decoration",
    banglaTitle: "বেবি শাওয়ার ডেকোরেশন",
    description: "Sweet and gentle decorations to celebrate your new arrival.",
    image: "https://i.ibb.co.com/QvQ1t1XR/45-PXL-20250614-115336274.jpg",
    images: [
      "https://i.ibb.co.com/ynYLm4hG/Adorable-blue-and-wh.jpg",
      "https://i.ibb.co.com/JFt9yP7y/Annaprashan-decoration-ghy.jpg",
      "https://i.ibb.co.com/rGt0VHb4/Twinkle-Twinkle-Little-Star-1st-Birthday-Decor-Navy-Gold-Blue-Arch.jpg",
      "https://i.ibb.co.com/C5nYWSJy/Hot-Air-Balloon-Birthday-Party-Oh-How-Time-Flies-Birthday-Party.jpg",
      "https://i.ibb.co.com/KcvgTJZg/download-35-5.jpg",
      "https://i.ibb.co.com/5gDcPcPm/download-36-3.jpg",
      "https://i.ibb.co.com/q39N4mH9/download-33-4.jpg",
      "https://i.ibb.co.com/bjnY6vsg/download-34-4.jpg",
      "https://i.ibb.co.com/GvkznFS1/download-32-4.jpg",
      "https://i.ibb.co.com/mFtQB64r/download-31-5.jpg",
      "https://i.ibb.co.com/Hf89vqwJ/download-30-4.jpg",
      "https://i.ibb.co.com/zhr55FbQ/download-29-3.jpg",
      "https://i.ibb.co.com/s9g319K8/Chrzest-wi-ty-i-roczek-Olisia.jpg",
      "https://i.ibb.co.com/gYVMK2F/baby-shower-decorations.jpg",
      "https://i.ibb.co.com/wFTxZVx3/BABY-SHOWER-DECORATION-Baby-Shower-Reel-Baby-Shower-Vibes-Baby-Shower-Inspo-Baby-Shower-Memories-bab.jpg",
      "https://i.ibb.co.com/8V3yfph/Baby-Shower-Decor-in-NCR-Delhi-India.jpg",
      "https://i.ibb.co.com/Y7sn8nrJ/Baby-Shower-Decor-babyshower-decor-balloons.jpg",
      "https://i.ibb.co.com/v6VNrS75/Baby-boy-balloons-backdrop-decoration.jpg",
      "https://i.ibb.co.com/LhqxHMjJ/Arch-Chiara-Backdrop-Cover-Stand-Hot-air-Balloon-Blue-Custom-Baby-Shower-Bridal-Shower-Birthday-Part.jpg"
    ],
    packages: [],
  },
  {
    id: "lighting-decor",
    title: "Road & Ceiling Lighting Decoration",
    banglaTitle: "রোড ও সিলিং লাইটিং ডেকোরেশন",
    description: "Professional lighting decoration for roads and ceilings to create a stunning atmosphere.",
    image: "https://i.ibb.co.com/5HGBh8z/4431.jpg",
    images: [
      "https://i.ibb.co.com/3YG2BTw2/23854.jpg",
      "https://i.ibb.co.com/JwxwtzWx/3394.jpg",
      "https://i.ibb.co.com/PGJPB4pm/3392.jpg",
      "https://i.ibb.co.com/qFsGNHsp/3398.jpg",
      "https://i.ibb.co.com/Y42tQTD1/4005.jpg",
      "https://i.ibb.co.com/5HGBh8z/4431.jpg",
      "https://i.ibb.co.com/WWBDVLJL/4432.jpg",
      "https://i.ibb.co.com/spQBt3xM/22423.jpg",
      "https://i.ibb.co.com/yFXxKn17/17158.jpg",
      "https://i.ibb.co.com/dTv1b8q/23293.jpg",
      "https://i.ibb.co.com/v4s5J8cM/22781.jpg",
      "https://i.ibb.co.com/MxQWdnYC/23860.jpg"
    ],
    packages: [],
  },
  {
    id: "wedding-night-room",
    title: "Wedding Night Room Decoration",
    banglaTitle: "বিয়ের রাতের রুম ডেকোরেশন",
    description: "Romantic and luxurious room decoration for the wedding night.",
    image: "https://i.ibb.co.com/sphWX9zJ/8641-jpg.jpg",
    images: ["https://picsum.photos/seed/weddingroom/800/600"],
    packages: WeddingNightRoomPackages,
  },
  {
    id: "wedding-car",
    title: "Wedding Car Decoration",
    banglaTitle: "বিয়ের গাড়ি ডেকোরেশন",
    description: "Elegant car decoration to make the wedding ride special.",
    image: "https://i.ibb.co.com/NdgHKqdW/download-36.jpg",
    images: ["https://picsum.photos/seed/weddingcar/800/600"],
    packages: WeddingCarPackages,
  },
  {
    id: "bride-groom-garlands",
    title: "Bride & Groom Flower Garlands",
    banglaTitle: "বর-কনেকে ফুলের মালা",
    description: "Fresh and beautiful flower garlands for bride and groom.",
    image: "https://i.ibb.co.com/bg5GDwzs/bor-2.jpg",
    images: [
      "https://i.ibb.co.com/rRZg0904/download-34-2.jpg",
      "https://i.ibb.co.com/v6PGpPTT/download-35-3.jpg",
      "https://i.ibb.co.com/q3XL1W90/download-36-1.jpg",
      "https://i.ibb.co.com/5X9N1MTf/Indian-Wedding-Mala-Red-White-Gold.jpg",
      "https://i.ibb.co.com/XrFNrc61/Just-a-cute-couple-we-are-crushing-on.jpg",
      "https://i.ibb.co.com/Z17rfBzB/Sangavi-Maalai-sangavimaalai-Instagram-photos-and-videos.jpg",
      "https://i.ibb.co.com/b5DMBqyg/Wedding-Flower-Garlands.jpg",
      "https://i.ibb.co.com/fzKxyt3g/download-29-1.jpg",
      "https://i.ibb.co.com/5h54vjLx/download-30-2.jpg",
      "https://i.ibb.co.com/TBkhPTTM/download-31-3.jpg",
      "https://i.ibb.co.com/Xcvnfrn/download-32-2.jpg",
      "https://i.ibb.co.com/xwDStB3/download-33-2.jpg"
    ],
    packages: [],
  },
  {
    id: "selfie-booth",
    title: "Selfie Booth",
    banglaTitle: "সেলফি বুথ",
    description: "A fun and stylish selfie booth setup for guests to capture memorable moments during weddings and special events.",
    image: "https://i.ibb.co.com/Q3RWm1N3/Sarvesh-event.jpg",
    images: [
      "https://i.ibb.co.com/VWcSfHrx/download-49-1.jpg",
      "https://i.ibb.co.com/v6Yw55cQ/download-47-1.jpg",
      "https://i.ibb.co.com/rf2RBSn0/download-46-1.jpg",
      "https://i.ibb.co.com/4g2ns4Pm/download-43-1.jpg",
      "https://i.ibb.co.com/bMSy2r1j/download-40-2.jpg",
      "https://i.ibb.co.com/RpMNDPkd/download-41-1.jpg",
      "https://i.ibb.co.com/5Wx5dK2t/download-34-5.jpg",
      "https://i.ibb.co.com/p69PRDZR/download-33-5.jpg",
      "https://i.ibb.co.com/sdrh3Yjg/download-32-5.jpg",
      "https://i.ibb.co.com/67yf787X/download-31-7.jpg",
      "https://i.ibb.co.com/fYThfkCL/download-29-5.jpg",
      "https://i.ibb.co.com/KxGL5H6s/birthday.jpg",
      "https://i.ibb.co.com/HpKPy65N/All-Red-Photobooth-for-your-wedding.jpg",
      "https://i.ibb.co.com/cSLk28qz/23874.jpg",
      "https://i.ibb.co.com/5h4hGs8w/7905.jpg",
      "https://i.ibb.co.com/b5HF4Tc3/7896.jpg",
      "https://i.ibb.co.com/1fZXwbJt/7893.jpg",
      "https://i.ibb.co.com/Wv2kZHSX/7892.jpg",
      "https://i.ibb.co.com/KzSvVfj5/3658.jpg",
      "https://i.ibb.co.com/tTz6QttZ/75th-Birthday-Decoration-Photobooth.jpg",
      "https://i.ibb.co.com/fzKLJD6x/bettertogether.jpg",
      "https://i.ibb.co.com/7xS3S5K6/2026.jpg",
      "https://i.ibb.co.com/3mJHKfPx/Wedding-stage-decoration-1.jpg",
      "https://i.ibb.co.com/zWWTz9Qf/The-joy-of-being-part-of-someone-s-special-day-and-seeing-the-love-they-share.jpg",
      "https://i.ibb.co.com/Kcd1S8wN/Wedding-Arch-Drape-Chiffon-Fabric-Draping-Curtain-Drapery-Wedding-Stage-Backdrop-Draping-Hanging.jpg",
      "https://i.ibb.co.com/RkByMh0c/SHRUTI-PRASHANTH-WEDDING.jpg",
      "https://i.ibb.co.com/wZYycVNy/Set-up-this-white-floral-minimal-decor-for-a-wedding-eventmanagement-eventplanner-eliteevent.jpg",
      "https://i.ibb.co.com/XrYVTN24/selfie-booth.jpg",
      "https://i.ibb.co.com/Q3RWm1N3/Sarvesh-event.jpg",
      "https://i.ibb.co.com/rRt4P7yf/Sarvesh-Most-beautiful-wedding-decoration-weddingvenue-USAWedding-UKWedding-Europe-Wedding-Can.jpg",
      "https://i.ibb.co.com/HLzyt2Ch/Pravesh-Maurya.jpg",
      "https://i.ibb.co.com/pj5LDf4t/Photo-Booth-Decoration-1.jpg",
      "https://i.ibb.co.com/DPWXjCHZ/download-50-1.jpg"
    ],
    packages: [],
  }, ,
  {
    id: "palanquin-rental",
    title: "Wedding Palanquin Rental",
    banglaTitle: "বিয়ের পালকী ভাড়া",
    description: "Traditional palanquin rental with charming design for solemn entry.",
    image: "https://i.ibb.co.com/httff4V/Forever-in-love-decorgoals.jpg",
    images: [
      "https://i.ibb.co.com/DD5pknk2/download-29-4.jpg",
      "https://i.ibb.co.com/YBbKRbxd/Top-10-Awesome-Wedding-Planners-of-Mumbai-Weddingplz-Blog.jpg",
      "https://i.ibb.co.com/httff4V/Forever-in-love-decorgoals.jpg",
      "https://i.ibb.co.com/S47H2Z1G/download-31-6.jpg",
      "https://i.ibb.co.com/60dVWQBY/download-30-5.jpg"
    ],
    packages: [],
  },
  // {
  //   id: "sherwani-rental-sale",
  //   title: "Sherwani Rental & Sale",
  //   description: "Premium sherwani options available for rental and purchase.",
  //   image: "https://picsum.photos/seed/sherwani/800/600",
  //   images: ["https://picsum.photos/seed/sherwani/800/600"],
  //   packages: [],
  // },
  {
    id: "wedding-gate",
    title: "Wedding Gate Decoration",
    banglaTitle: "বিয়ের গেট ডেকোরেশন",
    description: "Beautiful gate decorations to welcome guests for your wedding.",
    image: "https://i.ibb.co.com/7JKVdvc1/Fairy-Tale-Wedding-with-Flower-Arches-and-Floating-Lanterns.jpg",
    images: ["https://picsum.photos/seed/weddinggate/800/600"],
    packages: WeddingGatePackages,
  },
];
