/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { BusinessInfo, Service } from './types';

export const BUSINESS_INFO: BusinessInfo = {
  name: "Chuadanga Event Planner",
  owner: "MD SHAHIN",
  phones: ["01717445854", "01825052535"],
  whatsapp: "01717445854",
  email: "bondhuttoflowerhouse@gmail.com",
  facebook: "https://www.facebook.com/weddingplanningcd",
};

const EngagementCeremonyPackages = [
  {
    id: "basic",
    name: "Basic Package",
    priceRange: "10k – 15k",
    description: "Simple yet elegant decoration for intimate gatherings.",
    images: [
      "/Image/engagement/Basic Package/compressed_Consuelo Hernandez(JPG).jpg.jpeg",
      "/Image/engagement/Basic Package/compressed_Create unforgettable memories with our elegant setups(JPG).jpg.jpeg",
      "/Image/engagement/Basic Package/compressed_Mohammad Tanveer(JPG).jpg.jpeg",
      "/Image/engagement/Basic Package/compressed_Tajinder Sehmi(JPG).jpg.jpeg",
      "/Image/engagement/Basic Package/compressed_𝘽𝙀𝙀𝘽𝘼(JPG).jpg.jpeg"
    ],
  },
  {
    id: "standard",
    name: "Standard Package",
    priceRange: "15k – 35k",
    description: "Beautiful medium-scale decoration with more floral arrangements.",
    images: [
      "/Image/engagement/Standard Package/compressed_FB_IMG_1773394787163.jpg.jpeg",
      "/Image/engagement/Standard Package/compressed_HarshitaandSeanEngagementMahaStudiosInc-1.jpg.jpeg",
      "/Image/engagement/Standard Package/compressed_MPQ_Events(JPG).jpg.jpeg",
      "/Image/engagement/Standard Package/compressed_Rakhi_Kumari(JPG).jpg.jpeg",
      "/Image/engagement/Standard Package/compressed_Reception(JPG).jpg.jpeg",
      "/Image/engagement/Standard Package/compressed_Vidhi_Gohil(JPG).jpg.jpeg",
      "/Image/engagement/Standard Package/compressed_wedding_decor(JPG).jpg.jpeg"
    ],
  },
  {
    id: "premium",
    name: "Premium Package",
    priceRange: "35k – 60k",
    description: "High-quality decoration with premium lighting and backdrop designs.",
    images: [
      "/Image/engagement/Premium Package/compressed_25037.jpg.jpeg",
      "/Image/engagement/Premium Package/compressed_25041.jpg.jpeg",
      "/Image/engagement/Premium Package/compressed_25045.jpg.jpeg",
      "/Image/engagement/Premium Package/compressed_25048.jpg.jpeg",
      "/Image/engagement/Premium Package/compressed_25050.jpg.jpeg",
      "/Image/engagement/Premium Package/compressed_25052.jpg.jpeg"
    ],
  },
  {
    id: "royal",
    name: "Royal Package",
    priceRange: "60k+",
    description: "Luxury decoration for grand events with exquisite details and grand stages.",
    images: [
      "/Image/engagement/Royal Package/compressed_1510.jpg (2).jpeg",
      "/Image/engagement/Royal Package/compressed_25037.jpg.jpeg",
      "/Image/engagement/Royal Package/compressed_25041.jpg.jpeg",
      "/Image/engagement/Royal Package/compressed_25045.jpg.jpeg",
      "/Image/engagement/Royal Package/compressed_25048.jpg.jpeg",
      "/Image/engagement/Royal Package/compressed_25050.jpg.jpeg",
      "/Image/engagement/Royal Package/compressed_25052.jpg.jpeg",
      "/Image/engagement/Royal Package/compressed_25063.jpg.jpeg",
      "/Image/engagement/Royal Package/compressed_25067.jpg.jpeg",
      "/Image/engagement/Royal Package/compressed_25069.jpg.jpeg",
      "/Image/engagement/Royal Package/compressed_25073.jpg.jpeg",
      "/Image/engagement/Royal Package/compressed_3360.jpg (2).jpeg",
      "/Image/engagement/Royal Package/compressed_3641.jpg (2).jpeg",
      "/Image/engagement/Royal Package/compressed_8439.jpg (1).jpeg"
    ],
  },
];

const WeddingCarPackages = [
  {
    id: "basic",
    name: "Basic Package",
    priceRange: "10k – 15k",
    description: "Simple yet elegant decoration for intimate gatherings.",
    images: [
      "/Image/wedding-car/Basic Package/compressed_Babar Flower.jpg.jpg",
      "/Image/wedding-car/Basic Package/compressed_Car decor idea.jpg",
      "/Image/wedding-car/Basic Package/compressed_Car decoration flower.jpg",
      "/Image/wedding-car/Basic Package/compressed_download (30).jpg",
      "/Image/wedding-car/Basic Package/compressed_download (31).jpg",
      "/Image/wedding-car/Basic Package/compressed_download (32).jpg",
      "/Image/wedding-car/Basic Package/compressed_download (50).jpg",
      "/Image/wedding-car/Basic Package/compressed_download (52).jpg",
      "/Image/wedding-car/Basic Package/compressed_download (54).jpg",
      "/Image/wedding-car/Basic Package/compressed_GELINA~1.JPG",
      "/Image/wedding-car/Basic Package/compressed_Wedding BMW Car on Rent in Patna.jpg",
      "/Image/wedding-car/Basic Package/compressed_Wedding Car Decoration.jpg",
      "/Image/wedding-car/Basic Package/compressed_Wedding.jpg",
      "/Image/wedding-car/Basic Package/compressed_🚖 7 Seater Fortuner One Way Taxi on Rent in Chandigarh _ GTBTravels34 🚖.jpg"
    ],
  },
  {
    id: "standard",
    name: "Standard Package",
    priceRange: "15k – 35k",
    description: "Beautiful medium-scale decoration with more floral arrangements.",
    images: [
      "/Image/wedding-car/Standard Package/compressed_Babar Flower.jpg.jpg",
      "/Image/wedding-car/Standard Package/compressed_Car decor idea.jpg",
      "/Image/wedding-car/Standard Package/compressed_Car decoration flower.jpg",
      "/Image/wedding-car/Standard Package/compressed_download (30).jpg",
      "/Image/wedding-car/Standard Package/compressed_download (31).jpg",
      "/Image/wedding-car/Standard Package/compressed_download (32).jpg",
      "/Image/wedding-car/Standard Package/compressed_download (50).jpg",
      "/Image/wedding-car/Standard Package/compressed_download (52).jpg",
      "/Image/wedding-car/Standard Package/compressed_download (54).jpg",
      "/Image/wedding-car/Standard Package/compressed_GELINA~1.JPG",
      "/Image/wedding-car/Standard Package/compressed_Wedding BMW Car on Rent in Patna.jpg",
      "/Image/wedding-car/Standard Package/compressed_Wedding Car Decoration.jpg",
      "/Image/wedding-car/Standard Package/compressed_Wedding.jpg",
      "/Image/wedding-car/Standard Package/compressed_🚖 7 Seater Fortuner One Way Taxi on Rent in Chandigarh _ GTBTravels34 🚖.jpg"
    ],
  },
  {
    id: "premium",
    name: "Premium Package",
    priceRange: "35k – 60k",
    description: "High-quality decoration with premium lighting and backdrop designs.",
    images: [
      "/Image/wedding-car/Premium Package/compressed_20 Best Wedding Car Decoration Ideas In India 2026.jpg",
      "/Image/wedding-car/Premium Package/compressed_car weeding shadi.jpg",
      "/Image/wedding-car/Premium Package/compressed_Car.jpg",
      "/Image/wedding-car/Premium Package/compressed_download (1) (3).jpg",
      "/Image/wedding-car/Premium Package/compressed_download (32) (1).jpg",
      "/Image/wedding-car/Premium Package/compressed_download (40).jpg",
      "/Image/wedding-car/Premium Package/compressed_download (49).jpg",
      "/Image/wedding-car/Premium Package/compressed_download (51).jpg",
      "/Image/wedding-car/Premium Package/compressed_FASHIO~1.JPG",
      "/Image/wedding-car/Premium Package/compressed_𝐋𝐮𝐱𝐮𝐫𝐲 𝐖𝐞𝐝𝐝𝐢𝐧𝐠 𝐑𝐢𝐝𝐞_ 𝐍𝐢𝐚𝐳 𝐑𝐞𝐧𝐭 𝐚 𝐂𝐚𝐫_𝐬 𝐄𝐱𝐜𝐥𝐮𝐬𝐢𝐯𝐞 𝐅𝐥𝐞𝐞𝐭💫.jpg"
    ],
  },
  {
    id: "royal",
    name: "Royal Package",
    priceRange: "60k+",
    description: "Luxury decoration for grand events with exquisite details and grand stages.",
    images: [
      "/Image/wedding-car/Royal Package/compressed_car Decoration.jpg",
      "/Image/wedding-car/Royal Package/compressed_Celebrations25 WeddingWire2026 car decorated (1).jpg",
      "/Image/wedding-car/Royal Package/compressed_download (30) (1).jpg",
      "/Image/wedding-car/Royal Package/compressed_download (31) (1).jpg",
      "/Image/wedding-car/Royal Package/compressed_download (33) (1).jpg",
      "/Image/wedding-car/Royal Package/compressed_download (34) (1).jpg",
      "/Image/wedding-car/Royal Package/compressed_download (35) (1).jpg",
      "/Image/wedding-car/Royal Package/compressed_download (36).jpg",
      "/Image/wedding-car/Royal Package/compressed_download (38).jpg",
      "/Image/wedding-car/Royal Package/compressed_download (39).jpg"
    ],
  },
];


const HaldiCeremonyPackages = [
  {
    id: "basic",
    name: "Basic Package",
    priceRange: "10k – 15k",
    description: "Simple yet elegant decoration for intimate gatherings.",
    images: [
      "/Image/haldi/Basic Package/compressed_10251.jpg.jpeg",
      "/Image/haldi/Basic Package/compressed_22780.jpg.jpeg",
      "/Image/haldi/Basic Package/compressed_22783.jpg.jpeg",
      "/Image/haldi/Basic Package/compressed_22786.jpg.jpeg",
      "/Image/haldi/Basic Package/compressed_22791.jpg.jpeg",
      "/Image/haldi/Basic Package/compressed_22792.jpg.jpeg"
    ],
  },
  {
    id: "standard",
    name: "Standard Package",
    priceRange: "15k – 35k",
    description: "Beautiful medium-scale decoration with more floral arrangements.",
    images: [
      "/Image/haldi/Standard Package/compressed_22415.jpg.jpeg",
      "/Image/haldi/Standard Package/compressed_22421.jpg.jpeg",
      "/Image/haldi/Standard Package/compressed_22452.jpg.jpeg",
      "/Image/haldi/Standard Package/compressed_22463.jpg.jpeg",
      "/Image/haldi/Standard Package/compressed_22782.jpg.jpeg",
      "/Image/haldi/Standard Package/compressed_22784.jpg.jpeg",
      "/Image/haldi/Standard Package/compressed_22787.jpg.jpeg",
      "/Image/haldi/Standard Package/compressed_22788.jpg.jpeg",
      "/Image/haldi/Standard Package/compressed_22790.jpg.jpeg",
      "/Image/haldi/Standard Package/compressed_3947.jpg.jpeg"
    ],
  },
  {
    id: "premium",
    name: "Premium Package",
    priceRange: "35k – 60k",
    description: "High-quality decoration with premium lighting and backdrop designs.",
    images: [
      "/Image/haldi/Premium Package/compressed_25262.jpg.jpeg",
      "/Image/haldi/Premium Package/compressed_25264.jpg.jpeg",
      "/Image/haldi/Premium Package/compressed_25266.jpg.jpeg",
      "/Image/haldi/Premium Package/compressed_25268.jpg.jpeg",
      "/Image/haldi/Premium Package/compressed_25270.jpg.jpeg",
      "/Image/haldi/Premium Package/compressed_25272.jpg.jpeg",
      "/Image/haldi/Premium Package/compressed_25276.jpg.jpeg",
      "/Image/haldi/Premium Package/compressed_25286.jpg.jpeg",
      "/Image/haldi/Premium Package/compressed_25290.jpg.jpeg",
      "/Image/haldi/Premium Package/compressed_25293.jpg.jpeg",
      "/Image/haldi/Premium Package/compressed_25297.jpg.jpeg",
      "/Image/haldi/Premium Package/compressed_25299.jpg.jpeg",
      "/Image/haldi/Premium Package/compressed_25301.jpg.jpeg",
      "/Image/haldi/Premium Package/compressed_25305.jpg.jpeg"
    ],
  },
  {
    id: "royal",
    name: "Royal Package",
    priceRange: "60k+",
    description: "Luxury decoration for grand events with exquisite details and grand stages.",
    images: [
      "/Image/haldi/Royal Package/compressed_15868.jpg.jpeg",
      "/Image/haldi/Royal Package/compressed_17033.jpg.jpeg",
      "/Image/haldi/Royal Package/compressed_22116.jpg.jpeg",
      "/Image/haldi/Royal Package/compressed_22424.jpg.jpeg",
      "/Image/haldi/Royal Package/compressed_22467.jpg.jpeg",
      "/Image/haldi/Royal Package/compressed_22779.jpg.jpeg",
      "/Image/haldi/Royal Package/compressed_23177.jpg.jpeg",
      "/Image/haldi/Royal Package/compressed_23187.jpg.jpeg",
      "/Image/haldi/Royal Package/compressed_23238.jpg.jpeg",
      "/Image/haldi/Royal Package/compressed_23376.jpg.jpeg",
      "/Image/haldi/Royal Package/compressed_23848.jpg.jpeg",
      "/Image/haldi/Royal Package/compressed_23849.jpg.jpeg",
      "/Image/haldi/Royal Package/compressed_23861.jpg.jpeg",
      "/Image/haldi/Royal Package/compressed_24537.jpg.jpeg",
      "/Image/haldi/Royal Package/compressed_24548.jpg.jpeg",
      "/Image/haldi/Royal Package/compressed_24562.jpg.jpeg",
      "/Image/haldi/Royal Package/compressed_5455.jpg.jpeg",
      "/Image/haldi/Royal Package/compressed_7945.jpg.jpeg"
    ],
  },
];

const WeddingNightRoomPackages = [
  {
    id: "basic",
    name: "Basic Package",
    priceRange: "10k – 15k",
    description: "Simple yet elegant decoration for intimate gatherings.",
    images: [
      "/Image/wedding-night-room/Basic Package/compressed_25356.jpg.jpeg",
      "/Image/wedding-night-room/Basic Package/compressed_25358.jpg.jpeg",
      "/Image/wedding-night-room/Basic Package/compressed_25360.jpg.jpeg",
      "/Image/wedding-night-room/Basic Package/compressed_25362.jpg.jpeg",
      "/Image/wedding-night-room/Basic Package/compressed_25364.jpg.jpeg",
      "/Image/wedding-night-room/Basic Package/compressed_25366.jpg.jpeg",
      "/Image/wedding-night-room/Basic Package/compressed_25368.jpg.jpeg"
    ],
  },
  {
    id: "standard",
    name: "Standard Package",
    priceRange: "15k – 35k",
    description: "Beautiful medium-scale decoration with more floral arrangements.",
    images: [
      "/Image/wedding-night-room/Standard Package/compressed_download (1).jpg",
      "/Image/wedding-night-room/Standard Package/compressed_download (12).jpg",
      "/Image/wedding-night-room/Standard Package/compressed_download (2).jpg",
      "/Image/wedding-night-room/Standard Package/compressed_download (25).jpg",
      "/Image/wedding-night-room/Standard Package/compressed_download (26).jpg",
      "/Image/wedding-night-room/Standard Package/compressed_download (27).jpg",
      "/Image/wedding-night-room/Standard Package/compressed_download.jpg",
      "/Image/wedding-night-room/Standard Package/compressed_Romantic Canopy Bedroom Decor _ Elegant Boho Bedroom with Floral Drapes.jpg",
      "/Image/wedding-night-room/Standard Package/compressed_Teen Girl Royalty_ 16 Magical Princess Bedroom Inspirations Straight Out Of A Fairytale - Home Decor Palace.jpg",
      "/Image/wedding-night-room/Standard Package/compressed_Идеальная детская спальня.jpg"
    ],
  },
  {
    id: "premium",
    name: "Premium Package",
    priceRange: "35k – 60k",
    description: "High-quality decoration with premium lighting and backdrop designs.",
    images: [
      "/Image/wedding-night-room/Premium Package/compressed_Bedroom Decoration Ideas Wedding.jpg",
      "/Image/wedding-night-room/Premium Package/compressed_Celebrations25  WeddingWire2026 (1).jpg",
      "/Image/wedding-night-room/Premium Package/compressed_Celebrations25  WeddingWire2026 romantic bedroom (1).jpg",
      "/Image/wedding-night-room/Premium Package/compressed_download (1) (1).jpg",
      "/Image/wedding-night-room/Premium Package/compressed_download (2) (1).jpg",
      "/Image/wedding-night-room/Premium Package/compressed_download (29).jpg",
      "/Image/wedding-night-room/Premium Package/compressed_download (3).jpg",
      "/Image/wedding-night-room/Premium Package/compressed_Elegant Bedroom Design Ideas.jpg",
      "/Image/wedding-night-room/Premium Package/compressed_Sasta decore.jpg",
      "/Image/wedding-night-room/Premium Package/compressed___COZY~1.JPG"
    ],
  },
  {
    id: "royal",
    name: "Royal Package",
    priceRange: "60k+",
    description: "Luxury decoration for grand events with exquisite details and grand stages.",
    images: [
      "/Image/wedding-night-room/Royal Package/compressed_20 Romantic Wedding Room Decoration Ideas 2024.jpg",
      "/Image/wedding-night-room/Royal Package/compressed_22 Chic Bedroom Ideas to Embrace a Soft Country Aesthetic with Flower Decor.jpg",
      "/Image/wedding-night-room/Royal Package/compressed_8641.jpg.jpg",
      "/Image/wedding-night-room/Royal Package/compressed_download (1) (2).jpg",
      "/Image/wedding-night-room/Royal Package/compressed_download (2) (2).jpg",
      "/Image/wedding-night-room/Royal Package/compressed_download (25) (1).jpg",
      "/Image/wedding-night-room/Royal Package/compressed_download (27) (1).jpg",
      "/Image/wedding-night-room/Royal Package/compressed_download (4).jpg",
      "/Image/wedding-night-room/Royal Package/compressed_Hyderabad flower decor ✨ Bed decor for first night with roses & baby breathe.jpg",
      "/Image/wedding-night-room/Royal Package/compressed_romantic-1-bedroom.jpg.jpg",
      "/Image/wedding-night-room/Royal Package/compressed_Stunning Flower Arrangements That Instantly Brighten Any Room.jpg"
    ],
  },
];

const WeddingStagePackages = [
  {
    id: "basic",
    name: "Basic Package",
    priceRange: "10k – 15k",
    description: "Simple yet elegant decoration for intimate gatherings.",
    images: [
      "/Image/wedding-stage/Basic Package/compressed_25175.jpg (1).jpeg",
      "/Image/wedding-stage/Basic Package/compressed_25177.jpg (1).jpeg",
      "/Image/wedding-stage/Basic Package/compressed_25179.jpg (1).jpeg",
      "/Image/wedding-stage/Basic Package/compressed_25181.jpg (1).jpeg",
      "/Image/wedding-stage/Basic Package/compressed_25183.jpg (1).jpeg",
      "/Image/wedding-stage/Basic Package/compressed_25185.jpg (1).jpeg",
      "/Image/wedding-stage/Basic Package/compressed_25187.jpg (2).jpeg",
      "/Image/wedding-stage/Basic Package/compressed_25189.jpg (1).jpeg",
      "/Image/wedding-stage/Basic Package/compressed_25191.jpg (1).jpeg",
      "/Image/wedding-stage/Basic Package/compressed_25195.jpg (1).jpeg",
      "/Image/wedding-stage/Basic Package/compressed_25197.jpg (1).jpeg",
      "/Image/wedding-stage/Basic Package/compressed_25199.jpg (1).jpeg",
      "/Image/wedding-stage/Basic Package/compressed_25201.jpg (1).jpeg",
      "/Image/wedding-stage/Basic Package/compressed_25203.jpg (1).jpeg",
      "/Image/wedding-stage/Basic Package/compressed_25205.jpg (2).jpeg",
      "/Image/wedding-stage/Basic Package/compressed_25208.jpg (1).jpeg",
      "/Image/wedding-stage/Basic Package/compressed_25210.jpg (1).jpeg"
    ],
  },
  // {
  //   id: "standard",
  //   name: "Standard Package",
  //   priceRange: "15k – 35k",
  //   description: "Beautiful medium-scale decoration with more floral arrangements.",
  //   images: Array.from({ length: 9 }, (_, i) => `https://picsum.photos/seed/weddingstage-standard-${i}/800/600`),
  // },
  {
    id: "premium",
    name: "Premium Package",
    priceRange: "35k – 60k",
    description: "High-quality decoration with premium lighting and backdrop designs.",
    images: [
      "/Image/wedding-stage/Premium Package/compressed_1511.jpg.jpeg",
      "/Image/wedding-stage/Premium Package/compressed_23196.jpg.jpeg",
      "/Image/wedding-stage/Premium Package/compressed_24536.jpg.jpeg",
      "/Image/wedding-stage/Premium Package/compressed_24566.jpg.jpeg",
      "/Image/wedding-stage/Premium Package/compressed_25088.jpg.jpeg",
      "/Image/wedding-stage/Premium Package/compressed_25090.jpg.jpeg",
      "/Image/wedding-stage/Premium Package/compressed_25092.jpg.jpeg",
      "/Image/wedding-stage/Premium Package/compressed_25094.jpg.jpeg",
      "/Image/wedding-stage/Premium Package/compressed_25096.jpg.jpeg",
      "/Image/wedding-stage/Premium Package/compressed_25098.jpg.jpeg",
      "/Image/wedding-stage/Premium Package/compressed_25100.jpg.jpeg",
      "/Image/wedding-stage/Premium Package/compressed_25102.jpg.jpeg",
      "/Image/wedding-stage/Premium Package/compressed_25104.jpg.jpeg",
      "/Image/wedding-stage/Premium Package/compressed_25106.jpg.jpeg",
      "/Image/wedding-stage/Premium Package/compressed_3996.jpg.jpeg",
      "/Image/wedding-stage/Premium Package/compressed_7883.jpg.jpeg"
    ],
  },
  {
    id: "royal",
    name: "Royal Package",
    priceRange: "60k+",
    description: "Luxury decoration for grand events with exquisite details and grand stages.",
    images: [
      "/Image/wedding-stage/Royal Package/compressed_1510.jpg.jpeg",
      "/Image/wedding-stage/Royal Package/compressed_23197.jpg.jpeg",
      "/Image/wedding-stage/Royal Package/compressed_23209.jpg.jpeg",
      "/Image/wedding-stage/Royal Package/compressed_24528.jpg.jpeg",
      "/Image/wedding-stage/Royal Package/compressed_24529.jpg.jpeg",
      "/Image/wedding-stage/Royal Package/compressed_24534.jpg.jpeg",
      "/Image/wedding-stage/Royal Package/compressed_24542.jpg.jpeg",
      "/Image/wedding-stage/Royal Package/compressed_24544.jpg.jpeg",
      "/Image/wedding-stage/Royal Package/compressed_24550.jpg.jpeg",
      "/Image/wedding-stage/Royal Package/compressed_24551.jpg.jpeg",
      "/Image/wedding-stage/Royal Package/compressed_24557.jpg.jpeg",
      "/Image/wedding-stage/Royal Package/compressed_24558.jpg.jpeg",
      "/Image/wedding-stage/Royal Package/compressed_24559.jpg.jpeg",
      "/Image/wedding-stage/Royal Package/compressed_24561.jpg.jpeg",
      "/Image/wedding-stage/Royal Package/compressed_24565.jpg.jpeg",
      "/Image/wedding-stage/Royal Package/compressed_3360.jpg.jpeg",
      "/Image/wedding-stage/Royal Package/compressed_3641.jpg.jpeg"
    ],
  },
];

const WeddingGatePackages = [
  {
    id: "basic",
    name: "Basic Package",
    priceRange: "10k – 15k",
    description: "Simple yet elegant decoration for intimate gatherings.",
    images: [
      "/Image/wedding-gate/Basic Package/compressed_AnyConv.com__Decor exterior nunta.jpeg",
      "/Image/wedding-gate/Basic Package/compressed_AnyConv.com__Decoración con luces.jpeg",
      "/Image/wedding-gate/Basic Package/compressed_AnyConv.com__download (1).jpeg",
      "/Image/wedding-gate/Basic Package/compressed_AnyConv.com__download (2).jpeg",
      "/Image/wedding-gate/Basic Package/compressed_AnyConv.com__download (25).jpeg",
      "/Image/wedding-gate/Basic Package/compressed_AnyConv.com__download (26).jpeg",
      "/Image/wedding-gate/Basic Package/compressed_AnyConv.com__download.jpeg",
      "/Image/wedding-gate/Basic Package/compressed_AnyConv.com__Glam.jpeg",
      "/Image/wedding-gate/Basic Package/compressed_AnyConv.com__Pink wedding @luxealtars (1).jpeg",
      "/Image/wedding-gate/Basic Package/compressed_AnyConv.com__The arch from my wedding_ It was so gorgeous!.jpeg"
    ],
  },
  {
    id: "standard",
    name: "Standard Package",
    priceRange: "15k – 35k",
    description: "Beautiful medium-scale decoration with more floral arrangements.",
    images: [
      "/Image/wedding-gate/Standard Package/compressed_AnyConv.com__download (1) (1).jpeg",
      "/Image/wedding-gate/Standard Package/compressed_AnyConv.com__download (2) (1).jpeg",
      "/Image/wedding-gate/Standard Package/compressed_AnyConv.com__download (2) (1).jpeg",
      "/Image/wedding-gate/Standard Package/compressed_AnyConv.com__download (26) (1).jpeg",
      "/Image/wedding-gate/Standard Package/compressed_AnyConv.com__download (27).jpeg",
      "/Image/wedding-gate/Standard Package/compressed_AnyConv.com__download (28).jpeg",
      "/Image/wedding-gate/Standard Package/compressed_AnyConv.com__download (29).jpeg",
      "/Image/wedding-gate/Standard Package/compressed_AnyConv.com__download (30).jpeg",
      "/Image/wedding-gate/Standard Package/compressed_AnyConv.com__Entry Decoration _ simple entry decoration _ engagement ceremony entry decoration.jpeg",
      "/Image/wedding-gate/Standard Package/compressed_AnyConv.com__Entry.jpeg"
    ],
  },
  {
    id: "premium",
    name: "Premium Package",
    priceRange: "35k – 60k",
    description: "High-quality decoration with premium lighting and backdrop designs.",
    images: [
      "/Image/wedding-gate/Premium Package/compressed_AN7E77~1.JPE",
      "/Image/wedding-gate/Premium Package/compressed_AnyConv.com__19 Quinceañera Decorations Ideas That Feel Royal.jpeg",
      "/Image/wedding-gate/Premium Package/compressed_AnyConv.com__2 Post Wooden Arch.jpeg",
      "/Image/wedding-gate/Premium Package/compressed_AnyConv.com__85 Outdoor Wedding Arch Ideas for a Picture-Perfect Ceremony (1).jpeg",
      "/Image/wedding-gate/Premium Package/compressed_AnyConv.com__Backdrop Ideas.jpeg",
      "/Image/wedding-gate/Premium Package/compressed_AnyConv.com__Diseños exclusivas, de matrimonio, con encanto, en moda, de ideas de boda.jpeg",
      "/Image/wedding-gate/Premium Package/compressed_AnyConv.com__download (1) (2).jpeg",
      "/Image/wedding-gate/Premium Package/compressed_AnyConv.com__download (2) (2).jpeg",
      "/Image/wedding-gate/Premium Package/compressed_AnyConv.com__download (26) (2).jpeg",
      "/Image/wedding-gate/Premium Package/compressed_AnyConv.com__download (27) (1).jpeg",
      "/Image/wedding-gate/Premium Package/compressed_AnyConv.com__download (28) (1).jpeg",
      "/Image/wedding-gate/Premium Package/compressed_AnyConv.com__download (29) (1).jpeg",
      "/Image/wedding-gate/Premium Package/compressed_AnyConv.com__download (3).jpeg",
      "/Image/wedding-gate/Premium Package/compressed_AnyConv.com__download (30) (1).jpeg",
      "/Image/wedding-gate/Premium Package/compressed_AnyConv.com__download (31).jpeg",
      "/Image/wedding-gate/Premium Package/compressed_AnyConv.com__download (32).jpeg",
      "/Image/wedding-gate/Premium Package/compressed_AnyConv.com__download (33).jpeg",
      "/Image/wedding-gate/Premium Package/compressed_AnyConv.com__Dreamy entrance backdrop for your wedding.jpeg",
      "/Image/wedding-gate/Premium Package/compressed_AnyConv.com__Dreamy Outdoor Wedding Arch Inspiration_ Romantic Lakeside Ceremony.jpeg",
      "/Image/wedding-gate/Premium Package/compressed_AnyConv.com__Dreamy Wedding Flower Decorations.jpeg",
      "/Image/wedding-gate/Premium Package/compressed_AnyConv.com__Pathway Decoration using white & orange clothes and flowers.jpeg",
      "/Image/wedding-gate/Premium Package/compressed_AnyConv.com__Pink roses_ How about white roses_ Maybe a blush one or two_ We’ll take ‘em all! 🌷🌹.jpeg",
      "/Image/wedding-gate/Premium Package/compressed_AnyConv.com__Romantic Wedding Theme Ideas for 2025 Brides.jpeg",
      "/Image/wedding-gate/Premium Package/compressed_AnyConv.com__Transform Your Wedding with a Rococo Forest Theme.jpeg",
      "/Image/wedding-gate/Premium Package/compressed_AnyConv.com__wedding aesthetic.jpeg",
      "/Image/wedding-gate/Premium Package/compressed_AnyConv.com__Yellow Entrance Arch.jpeg"
    ],
  },
  {
    id: "royal",
    name: "Royal Package",
    priceRange: "60k+",
    description: "Luxury decoration for grand events with exquisite details and grand stages.",
    images: [
      "/Image/wedding-gate/Royal Package/compressed_15 Wedding Entrance Decor Ideas to Wow Your Guests Instantly.jpg",
      "/Image/wedding-gate/Royal Package/compressed_23 Romantic Wedding Arch Ideas to Make Your Ceremony Absolutely Magical.jpg",
      "/Image/wedding-gate/Royal Package/compressed_3923.jpg.jpg",
      "/Image/wedding-gate/Royal Package/compressed_3928.jpg.jpg",
      "/Image/wedding-gate/Royal Package/compressed_3932.jpg.jpg",
      "/Image/wedding-gate/Royal Package/compressed_3960.jpg.jpg",
      "/Image/wedding-gate/Royal Package/compressed_Destination Wedding Dreams • Plan Your Perfect Day.jpg",
      "/Image/wedding-gate/Royal Package/compressed_download (35) (2).jpg",
      "/Image/wedding-gate/Royal Package/compressed_Fairy Tale Wedding with Flower Arches and Floating Lanterns.jpg",
      "/Image/wedding-gate/Royal Package/compressed_✨ Elegant Wedding Inspiration ✨.jpg"
    ],
  },
];

const MehediStagePackages = [
  {
    id: "basic",
    name: "Basic Mehedi Stage",
    priceRange: "8k – 12k",
    description: "Simple Mehedi stage decoration with basic floral and fabric backdrop.",
    images: [
      "/Image/mehndi/Basic Package/compressed_mehedi-besic-1.jpeg",
      "/Image/mehndi/Basic Package/compressed_mehedi-besic-2.jpeg",
      "/Image/mehndi/Basic Package/compressed_mehedi-besic-3.jpeg",
      "/Image/mehndi/Basic Package/compressed_mehedi-besic-4.jpeg",
      "/Image/mehndi/Basic Package/compressed_mehedi-besic-5.jpeg"
    ],
  },
  {
    id: "standard",
    name: "Standard Mehedi Stage",
    priceRange: "12k – 25k",
    description: "Colorful Mehedi stage with floral decorations, lights, and elegant seating.",
    images: [
      "/Image/mehndi/Standard Package/compressed_mehedi-standard-1.jpeg",
      "/Image/mehndi/Standard Package/compressed_mehedi-standard-2.jpeg",
      "/Image/mehndi/Standard Package/compressed_mehedi-standard-3.jpeg",
      "/Image/mehndi/Standard Package/compressed_mehedi-standard-4.jpeg",
      "/Image/mehndi/Standard Package/compressed_mehedi-standard-5.jpeg"
    ],
  },
  {
    id: "premium",
    name: "Premium Mehedi Stage",
    priceRange: "25k – 45k",
    description: "Premium Mehedi stage with vibrant colors, flower canopy, and designer backdrop.",
    images: [
      "/Image/mehndi/Premium Package/compressed_mehedi-premi-1.jpeg",
      "/Image/mehndi/Premium Package/compressed_mehedi-premi-2.jpeg",
      "/Image/mehndi/Premium Package/compressed_mehedi-premi-3.jpeg",
      "/Image/mehndi/Premium Package/compressed_mehedi-premi-4.jpeg"
    ],
  },
  {
    id: "royal",
    name: "Royal Mehedi Stage",
    priceRange: "45k+",
    description: "Grand Mehedi stage with luxury seating, heavy floral work, and premium lighting.",
    images: [
      "/Image/mehndi/Royal Package/compressed_mehedi-royel-1.jpeg",
      "/Image/mehndi/Royal Package/compressed_mehedi-royel-2.jpeg",
      "/Image/mehndi/Royal Package/compressed_mehedi-royel-3.jpeg",
      "/Image/mehndi/Royal Package/compressed_mehedi-royel-4.jpeg",
      "/Image/mehndi/Royal Package/compressed_mehedi-royel-5.jpeg"
    ],
  },
];

export const SERVICES: Service[] = [
  {
    id: "haldi",
    title: "Haldi Ceremony Decoration",
    banglaTitle: "হলদি অনুষ্ঠান সজ্জা",
    description: "Vibrant yellow-themed decorations for your traditional Haldi ceremony.",
    image: "/Image/haldi/Royal Package/compressed_24537.jpg.jpeg",
    images: [
      "/Image/haldi/Basic Package/compressed_24537.jpg.jpeg",
      "/Image/haldi/Premium Package/compressed_24536.jpg.jpeg",
      "/Image/haldi/Royal Package/compressed_24534.jpg.jpeg"
    ],
    packages: HaldiCeremonyPackages,
  },
  {
    id: "mehndi",
    title: "Mehndi Ceremony Decoration",
    banglaTitle: "মেহেদি অনুষ্ঠান সজ্জা",
    description: "Creative and colorful setups for a memorable Mehndi night.",
    image: "/Image/mehndi/Basic Package/compressed_mehedi-besic-1.jpeg",
    images: [
      "/Image/mehndi/Basic Package/compressed_mehedi-besic-1.jpeg",
      "/Image/mehndi/Premium Package/compressed_mehedi-premi-1.jpeg",
      "/Image/mehndi/Royal Package/compressed_mehedi-royel-1.jpeg"
    ],
    packages: MehediStagePackages,
  },


  {
    id: "wedding-stage",
    title: "Wedding Stage Decoration",
    banglaTitle: "বিয়ের স্টেজ ডেকোরেশন",
    description: "Grand and elegant stage designs for your big day.",
    image: "/Image/wedding-stage/Basic Package/compressed_25175.jpg (1).jpeg",
    images: [
      "/Image/wedding-stage/Basic Package/compressed_25175.jpg (1).jpeg",
      "/Image/wedding-stage/Premium Package/compressed_1511.jpg.jpeg",
      "/Image/wedding-stage/Royal Package/compressed_1510.jpg.jpeg"
    ],
    packages: WeddingStagePackages,
  },
  {
    id: "reception-stage",
    title: "Wedding Reception Stage Decoration",
    banglaTitle: "বিয়ের রিসেপশন স্টেজ ডেকোরেশন",
    description: "Sophisticated and modern reception stage setups.",
    image: "/Image/reception-stage/compressed_1510.jpg (1).jpeg",
    images: [
      "/Image/reception-stage/compressed_1510.jpg (1).jpeg",
      "/Image/reception-stage/compressed_15174.jpg.jpeg",
      "/Image/reception-stage/compressed_22111.jpg.jpeg",
      "/Image/reception-stage/compressed_22113.jpg.jpeg",
      "/Image/reception-stage/compressed_22118.jpg.jpeg",
      "/Image/reception-stage/compressed_22732.jpg.jpeg",
      "/Image/reception-stage/compressed_23174.jpg.jpeg",
      "/Image/reception-stage/compressed_23175.jpg.jpeg",
      "/Image/reception-stage/compressed_23180.jpg.jpeg",
      "/Image/reception-stage/compressed_23184.jpg.jpeg",
      "/Image/reception-stage/compressed_23197.jpg (1).jpeg",
      "/Image/reception-stage/compressed_23205.jpg.jpeg",
      "/Image/reception-stage/compressed_23257.jpg.jpeg",
      "/Image/reception-stage/compressed_24528.jpg (1).jpeg",
      "/Image/reception-stage/compressed_24529.jpg (1).jpeg",
      "/Image/reception-stage/compressed_24534.jpg (1).jpeg",
      "/Image/reception-stage/compressed_24550.jpg (1).jpeg",
      "/Image/reception-stage/compressed_24551.jpg (1).jpeg",
      "/Image/reception-stage/compressed_24557.jpg (1).jpeg",
      "/Image/reception-stage/compressed_24558.jpg (1).jpeg",
      "/Image/reception-stage/compressed_24559.jpg (1).jpeg",
      "/Image/reception-stage/compressed_24565.jpg (1).jpeg",
      "/Image/reception-stage/compressed_3360.jpg (1).jpeg",
      "/Image/reception-stage/compressed_3641.jpg (1).jpeg",
      "/Image/reception-stage/compressed_8439.jpg.jpeg"
    ],
    packages: [],
  },
  {
    id: "birthday",
    title: "Birthday Stage Decoration",
    banglaTitle: "জন্মদিনের স্টেজ ডেকোরেশন",
    description: "Fun and themed decorations for all ages.",
    image: "/Image/birthday/compressed_7935.jpg.jpeg",
    images: [
      "/Image/birthday/compressed_17034.jpg.jpeg",
      "/Image/birthday/compressed_3921.jpg.jpeg",
      "/Image/birthday/compressed_7934.jpg.jpeg",
      "/Image/birthday/compressed_7935.jpg.jpeg",
      "/Image/birthday/compressed_7936.jpg.jpeg",
      "/Image/birthday/compressed_7937.jpg.jpeg"
    ],
    packages: [],
  },
  {
    id: "engagement",
    title: "Engagement Ceremony Stage Decoration",
    banglaTitle: "এঙ্গেজমেন্ট অনুষ্ঠানের স্টেজ ডেকোরেশন",
    description: "Romantic and classy setups for your engagement.",
    image: "/Image/engagement/Basic Package/compressed_Consuelo Hernandez(JPG).jpg.jpeg",
    images: [
      "/Image/engagement/Basic Package/compressed_1510.jpg.jpeg",
      "/Image/engagement/Premium Package/compressed_1510.jpg (1).jpeg",
      "/Image/engagement/Royal Package/compressed_1510.jpg (2).jpeg"
    ],
    packages: EngagementCeremonyPackages,
  },
  {
    id: "islamic-mahfil",
    title: "Islamic Mahfil Stage Decoration",
    banglaTitle: "ইসলামিক মহফিল স্টেজ ডেকোরেশন",
    description: "Respectful and beautiful arrangements for religious gatherings.",
    image: "/Image/islamic-mahfil/compressed_mahfil-1.jpeg",
    images: [
      "/Image/islamic-mahfil/compressed_mahfil-1.jpeg",
      "/Image/islamic-mahfil/compressed_mahfil-2.jpeg",
      "/Image/islamic-mahfil/compressed_mahfil-3.jpeg",
      "/Image/islamic-mahfil/compressed_mahfil-4.jpeg",
      "/Image/islamic-mahfil/compressed_mahfil-5.jpeg",
      "/Image/islamic-mahfil/compressed_mahfil-6.jpeg",
      "/Image/islamic-mahfil/compressed_mahfil-7.jpeg",
      "/Image/islamic-mahfil/compressed_mahfil-8.jpeg",
      "/Image/islamic-mahfil/compressed_mahfil-9.jpeg",
      "/Image/islamic-mahfil/compressed_mahfil-10.jpeg"
    ],
    packages: [],
  },
  {
    id: "building-lighting-stage-decoration",
    title: "Building Lighting Stage Decoration",
    banglaTitle: "বিল্ডিং লাইটিং স্টেজ ডেকোরেশন",
    description: "Beautiful lighting decoration for buildings and stages, creating a stunning and festive atmosphere for weddings and special events.",
    image: "/Image/building-lighting-stage-decoration/compressed_download (29) (2).jfif",
    images: [
      "/Image/building-lighting-stage-decoration/compressed_download (29) (2).jfif",
      "/Image/building-lighting-stage-decoration/compressed_download (30) (2).jfif",
      "/Image/building-lighting-stage-decoration/compressed_download (31) (2).jfif",
      "/Image/building-lighting-stage-decoration/compressed_download (32) (1).jfif",
      "/Image/building-lighting-stage-decoration/compressed_download (33) (1).jfif",
      "/Image/building-lighting-stage-decoration/compressed_download (34) (2).jfif",
      "/Image/building-lighting-stage-decoration/compressed_download (35) (1).jfif",
      "/Image/building-lighting-stage-decoration/compressed_download (36) (1).jfif",
      "/Image/building-lighting-stage-decoration/compressed_download (40).jfif",
      "/Image/building-lighting-stage-decoration/compressed_download (41).jfif",
      "/Image/building-lighting-stage-decoration/compressed_Entrance gate decorations for sangeet.jfif",
      "/Image/building-lighting-stage-decoration/compressed_Farm house🤑.jfif",
      "/Image/building-lighting-stage-decoration/compressed_My Sweet Home 💗🏡.jfif"
    ],
    packages: [],
  },
  {
    id: "baby-shower",
    title: "Baby Shower Decoration",
    banglaTitle: "বেবি শাওয়ার ডেকোরেশন",
    description: "Sweet and gentle decorations to celebrate your new arrival.",
    image: "/Image/baby-shower/compressed_ADORAB~1.JPG",
    images: [
      "/Image/baby-shower/compressed_ADORAB~1.JPG",
      "/Image/baby-shower/compressed_baby shower decorations.jfif",
      "/Image/baby-shower/compressed_Baby Shower Decor_ #babyshower #decor #balloons.jfif",
      "/Image/baby-shower/compressed_Chrzest Święty i roczek Olisia 🤍.jfif",
      "/Image/baby-shower/compressed_download (29) (1).jfif",
      "/Image/baby-shower/compressed_download (30) (1).jfif",
      "/Image/baby-shower/compressed_download (31) (1).jfif",
      "/Image/baby-shower/compressed_download (32).jfif",
      "/Image/baby-shower/compressed_download (33).jfif",
      "/Image/baby-shower/compressed_download (34) (1).jfif",
      "/Image/baby-shower/compressed_download (35).jfif",
      "/Image/baby-shower/compressed_download (36).jfif",
      "/Image/baby-shower/compressed_Hot Air Balloon Birthday Party _ Oh How Time Flies Birthday Party.jfif",
      "/Image/baby-shower/compressed_Twinkle Twinkle Little Star 1st Birthday Decor_ Navy, Gold & Blue Arch.jfif"
    ],
    packages: [],
  },
  {
    id: "lighting-decor",
    title: "Road & Ceiling Lighting Decoration",
    banglaTitle: "রোড ও সিলিং লাইটিং ডেকোরেশন",
    description: "Professional lighting decoration for roads and ceilings to create a stunning atmosphere.",
    image: "/Image/lighting-decor/compressed_17158.jpg.jpeg",
    images: [
      "/Image/lighting-decor/compressed_17158.jpg.jpeg",
      "/Image/lighting-decor/compressed_22423.jpg.jpeg",
      "/Image/lighting-decor/compressed_22781.jpg.jpeg",
      "/Image/lighting-decor/compressed_23293.jpg.jpeg",
      "/Image/lighting-decor/compressed_23854.jpg.jpeg",
      "/Image/lighting-decor/compressed_23860.jpg - Copy.jpeg",
      "/Image/lighting-decor/compressed_3392.jpg.jpeg",
      "/Image/lighting-decor/compressed_3394.jpg.jpeg",
      "/Image/lighting-decor/compressed_3398.jpg.jpeg",
      "/Image/lighting-decor/compressed_4005.jpg.jpeg",
      "/Image/lighting-decor/compressed_4431.jpg.jpeg",
      "/Image/lighting-decor/compressed_4432.jpg.jpeg"
    ],
    packages: [],
  },
  {
    id: "wedding-night-room",
    title: "Wedding Night Room Decoration",
    banglaTitle: "বিয়ের রাতের রুম ডেকোরেশন",
    description: "Romantic and luxurious room decoration for the wedding night.",
    image: "/Image/wedding-night-room/Basic Package/compressed_25356.jpg.jpeg",
    images: [
      "/Image/wedding-night-room/Basic Package/compressed_25356.jpg.jpeg",
      "/Image/wedding-night-room/Premium Package/compressed_25356.jpg (1).jpeg",
      "/Image/wedding-night-room/Royal Package/compressed_25356.jpg (2).jpeg"
    ],
    packages: WeddingNightRoomPackages,
  },
  {
    id: "wedding-car",
    title: "Wedding Car Decoration",
    banglaTitle: "বিয়ের গাড়ি ডেকোরেশন",
    description: "Elegant car decoration to make the wedding ride special.",
    image: "/Image/wedding-car/Basic Package/compressed_Wedding Car Decoration.jpg",
    images: [
      "/Image/wedding-car/Basic Package/compressed_download (29).jfif",
      "/Image/wedding-car/Premium Package/compressed_download (29) (1).jfif",
      "/Image/wedding-car/Royal Package/compressed_download (29) (2).jfif"
    ],
    packages: WeddingCarPackages,
  },
  {
    id: "bride-groom-garlands",
    title: "Bride & Groom Flower Garlands",
    banglaTitle: "বর-কনেকে ফুলের মালা",
    description: "Fresh and beautiful flower garlands for bride and groom.",
    image: "/Image/bride-groom-garlands/compressed_download (29) (1).jpg",
    images: [
      "/Image/bride-groom-garlands/compressed_download (29) (1).jpg",
      "/Image/bride-groom-garlands/compressed_download (30) (2).jpg",
      "/Image/bride-groom-garlands/compressed_download (31) (3).jpg",
      "/Image/bride-groom-garlands/compressed_download (32) (2).jpg",
      "/Image/bride-groom-garlands/compressed_download (33) (2).jpg",
      "/Image/bride-groom-garlands/compressed_download (34) (2).jpg",
      "/Image/bride-groom-garlands/compressed_download (35) (3).jpg",
      "/Image/bride-groom-garlands/compressed_download (36) (1).jpg",
      "/Image/bride-groom-garlands/compressed_Indian Wedding Mala Red White Gold.jpg",
      "/Image/bride-groom-garlands/compressed_Just a cute couple we are crushing on❣️.jpg",
      "/Image/bride-groom-garlands/compressed_Sangavi Maalai (@sangavimaalai) • Instagram photos and videos.jpg",
      "/Image/bride-groom-garlands/compressed_Wedding Flower Garlands.jpg"
    ],
    packages: [],
  },
  {
    id: "selfie-booth",
    title: "Selfie Booth",
    banglaTitle: "সেলফি বুথ",
    description: "A fun and stylish selfie booth setup for guests to capture memorable moments during weddings and special events.",
    image: "/Image/selfie-booth/compressed_23254.jpg.jpeg",
    images: [
      "/Image/selfie-booth/compressed_23254.jpg.jpeg",
      "/Image/selfie-booth/compressed_23853.jpg.jpeg",
      "/Image/selfie-booth/compressed_23853.jpg.jpeg",
      "/Image/selfie-booth/compressed_3658.jpg.jpeg",
      "/Image/selfie-booth/compressed_3659.jpg.jpeg",
      "/Image/selfie-booth/compressed_75th Birthday Decoration _ Photobooth.jfif",
      "/Image/selfie-booth/compressed_7891.jpg.jpeg",
      "/Image/selfie-booth/compressed_7892.jpg.jpeg",
      "/Image/selfie-booth/compressed_7896.jpg.jpeg",
      "/Image/selfie-booth/compressed_7899.jpg.jpeg",
      "/Image/selfie-booth/compressed_7905.jpg.jpeg",
      "/Image/selfie-booth/compressed_8648.jpg.jpeg",
      "/Image/selfie-booth/compressed_All Red Photobooth for your wedding.jfif",
      "/Image/selfie-booth/compressed_Decoration for kids and function.jfif",
      "/Image/selfie-booth/compressed_download (34).jfif",
      "/Image/selfie-booth/compressed_download (44).jfif",
      "/Image/selfie-booth/compressed_download (47).jfif",
      "/Image/selfie-booth/compressed_download (48).jfif",
      "/Image/selfie-booth/compressed_download (49).jfif",
      "/Image/selfie-booth/compressed_download (50).jfif",
      "/Image/selfie-booth/compressed_download (51).jfif",
      "/Image/selfie-booth/compressed_download (52).jfif",
      "/Image/selfie-booth/compressed_download (53).jfif",
      "/Image/selfie-booth/compressed_download (54).jfif",
      "/Image/selfie-booth/compressed_download (55).jfif",
      "/Image/selfie-booth/compressed_download (56).jfif",
      "/Image/selfie-booth/compressed_Ide dekorasi pernikahan.jfif",
      "/Image/selfie-booth/compressed_Sarvesh event.jfif",
      "/Image/selfie-booth/compressed_Wedding stage decoration (1).jfif",
      "/Image/selfie-booth/compressed_wedding stage decoration.jfif",
      "/Image/selfie-booth/compressed_тренды свадебного декора 2026.jfif"
    ],
    packages: [],
  },
  {
    id: "palanquin-rental",
    title: "Wedding Palanquin Rental",
    banglaTitle: "বিয়ের পালকী ভাড়া",
    description: "Traditional palanquin rental with charming design for solemn entry.",
    image: "/Image/palanquin-rental/compressed_download (29).jfif",
    images: [
      "/Image/palanquin-rental/compressed_download (29).jfif",
      "/Image/palanquin-rental/compressed_download (30).jfif",
      "/Image/palanquin-rental/compressed_download (31).jfif",
      "/Image/palanquin-rental/compressed_download (30).jfif",
      "/Image/palanquin-rental/compressed_Top 10 Awesome Wedding Planners of Mumbai! - Weddingplz Blog.jfif"
    ],
    packages: [],
  },
  // {
  //   id: "sherwani-rental-sale",
  //   title: "Sherwani Rental & Sale",
  //   description: "Premium sherwani options available for rental and purchase.",
  //   image: "https://picsum.photos/seed/sherwani/800/600",
  //   images: ["https://picsum.photos/seed/sherwani/800/600"],
  //   packages: [],
  // },
  {
    id: "wedding-gate",
    title: "Wedding Gate Decoration",
    banglaTitle: "বিয়ের গেট ডেকোরেশন",
    description: "Beautiful gate decorations to welcome guests for your wedding.",
    image: "/Image/wedding-gate/Basic Package/compressed_AnyConv.com__Decor exterior nunta.jpeg",
    images: [
      "/Image/wedding-gate/Basic Package/compressed_AnyConv.com__Decor exterior nunta.jpeg",
      "/Image/wedding-gate/Premium Package/compressed_AN7E77~1.JPE",
      "/Image/wedding-gate/Royal Package/compressed_15 Wedding Entrance Decor Ideas to Wow Your Guests Instantly.jpg"
    ],
    packages: WeddingGatePackages,
  },
];
